// data.js — curated content pools for Daily.
// Daily items are chosen deterministically from the date so everyone
// sees the same content on a given day and it rotates every 24h.

const FUN_FACTS = [
  "Honey never spoils. Archaeologists have found 3,000-year-old honey in Egyptian tombs that's still perfectly edible.",
  "Octopuses have three hearts, nine brains, and blue blood.",
  "A day on Venus is longer than a year on Venus — it rotates slower than it orbits the Sun.",
  "Bananas are berries, but strawberries are not, botanically speaking.",
  "Wombat poop is cube-shaped, which keeps it from rolling away and helps mark territory.",
  "The Eiffel Tower can grow more than 15 cm taller in summer as the iron expands in the heat.",
  "Sharks existed before trees. Sharks date back ~450 million years; trees ~390 million.",
  "There are more possible games of chess than there are atoms in the observable universe.",
  "A group of flamingos is called a 'flamboyance.'",
  "Your stomach gets a new lining every few days because stomach acid would otherwise digest it.",
  "Hot water can freeze faster than cold water under certain conditions — the Mpemba effect.",
  "The shortest war in history lasted about 38 minutes (Anglo-Zanzibar War, 1896).",
  "Cats can't taste sweetness — they lack the receptor for it.",
  "The Great Wall of China is not visible from space with the naked eye, contrary to popular belief.",
  "Humans share about 60% of their DNA with bananas.",
  "A single bolt of lightning is about five times hotter than the surface of the Sun.",
  "Scotland's national animal is the unicorn.",
  "The dot over a lowercase 'i' or 'j' is called a 'tittle.'",
  "Sea otters hold hands while sleeping so they don't drift apart.",
  "Earth is the only planet not named after a god.",
  "An adult human is made up of about 7 octillion atoms.",
  "Polar bears have black skin under their translucent fur, which appears white.",
  "The inventor of the frisbee was turned into a frisbee — his ashes were molded into one after he died.",
  "There's enough DNA in your body to stretch from the Sun to Pluto and back ~17 times.",
  "A 'jiffy' is an actual unit of time: 1/100th of a second.",
  "Nintendo was founded in 1889 — originally making playing cards.",
  "Some turtles can breathe through their butts (cloacal respiration).",
  "The unicorn was once thought to be real and appears in ancient Greek natural-history texts.",
  "Saturn would float in water if you could find a bathtub big enough — it's less dense than water.",
  "The human nose can detect over one trillion distinct scents.",
  "Hummingbirds are the only birds that can fly backwards.",
  "The longest hiccupping spree lasted 68 years.",
  "Venus is the only planet that spins clockwise.",
  "A snail can sleep for up to three years.",
  "The fingerprints of koalas are so similar to humans' they've confused crime scenes.",
  "Bubble wrap was originally invented as wallpaper.",
  "The shortest complete sentence in English is 'I am.'",
  "More than half of the bones in your body are in your hands and feet.",
  "A cloud can weigh more than a million pounds.",
  "Sloths can hold their breath longer than dolphins — up to 40 minutes."
];

const RIDDLES = [
  { q: "I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?", a: "An echo." },
  { q: "The more of me you take, the more you leave behind. What am I?", a: "Footsteps." },
  { q: "What has keys but can't open locks, space but no room, and you can enter but can't go inside?", a: "A keyboard." },
  { q: "I'm tall when I'm young and short when I'm old. What am I?", a: "A candle." },
  { q: "What has hands but cannot clap?", a: "A clock." },
  { q: "What gets wetter the more it dries?", a: "A towel." },
  { q: "I have cities but no houses, mountains but no trees, and water but no fish. What am I?", a: "A map." },
  { q: "What can travel around the world while staying in a corner?", a: "A stamp." },
  { q: "The person who makes it has no need of it. The person who buys it has no use for it. The person who uses it can't see or feel it. What is it?", a: "A coffin." },
  { q: "What has a head, a tail, but no body?", a: "A coin." },
  { q: "What has many teeth but cannot bite?", a: "A comb." },
  { q: "What can you catch but not throw?", a: "A cold." },
  { q: "I'm light as a feather, yet the strongest person can't hold me for more than a few minutes. What am I?", a: "Your breath." },
  { q: "What goes up but never comes down?", a: "Your age." },
  { q: "What has one eye but cannot see?", a: "A needle." },
  { q: "What gets bigger the more you take away from it?", a: "A hole." },
  { q: "What has a neck but no head?", a: "A bottle." },
  { q: "What runs but never walks, has a bed but never sleeps?", a: "A river." },
  { q: "What can fill a room but takes up no space?", a: "Light." },
  { q: "I have branches, but no fruit, trunk, or leaves. What am I?", a: "A bank." },
  { q: "What kind of band never plays music?", a: "A rubber band." },
  { q: "What has words but never speaks?", a: "A book." },
  { q: "Forward I'm heavy, but backward I'm not. What am I?", a: "The word 'ton.'" },
  { q: "What building has the most stories?", a: "A library." },
  { q: "If you drop me I'm sure to crack, but smile at me and I'll smile back. What am I?", a: "A mirror." },
  { q: "What has a thumb and four fingers but is not alive?", a: "A glove." },
  { q: "What invention lets you look right through a wall?", a: "A window." },
  { q: "What can you keep after giving it to someone?", a: "Your word." },
  { q: "I follow you all day long, but when the night comes I'm gone. What am I?", a: "Your shadow." },
  { q: "What has 13 hearts but no other organs?", a: "A deck of cards." }
];

const TRIVIA = [
  { q: "What is the largest planet in our solar system?", choices: ["Saturn", "Jupiter", "Neptune", "Earth"], correct: 1 },
  { q: "Which element has the chemical symbol 'Au'?", choices: ["Silver", "Aluminum", "Gold", "Argon"], correct: 2 },
  { q: "In what year did the first human land on the Moon?", choices: ["1965", "1969", "1972", "1959"], correct: 1 },
  { q: "What is the smallest prime number?", choices: ["0", "1", "2", "3"], correct: 2 },
  { q: "Which country is home to the kangaroo?", choices: ["Brazil", "South Africa", "Australia", "India"], correct: 2 },
  { q: "Who painted the Mona Lisa?", choices: ["Michelangelo", "Raphael", "Leonardo da Vinci", "Donatello"], correct: 2 },
  { q: "What is the hardest natural substance on Earth?", choices: ["Quartz", "Steel", "Diamond", "Titanium"], correct: 2 },
  { q: "How many continents are there on Earth?", choices: ["5", "6", "7", "8"], correct: 2 },
  { q: "What is the capital of Japan?", choices: ["Seoul", "Beijing", "Tokyo", "Bangkok"], correct: 2 },
  { q: "Which ocean is the largest?", choices: ["Atlantic", "Indian", "Arctic", "Pacific"], correct: 3 },
  { q: "What gas do plants primarily absorb from the atmosphere?", choices: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], correct: 2 },
  { q: "Who wrote 'Romeo and Juliet'?", choices: ["Charles Dickens", "William Shakespeare", "Mark Twain", "Jane Austen"], correct: 1 },
  { q: "What is the speed of light approximately?", choices: ["300,000 km/s", "30,000 km/s", "3,000 km/s", "3 million km/s"], correct: 0 },
  { q: "Which planet is known as the Red Planet?", choices: ["Venus", "Mars", "Mercury", "Jupiter"], correct: 1 },
  { q: "What is the largest mammal in the world?", choices: ["African elephant", "Blue whale", "Giraffe", "Hippopotamus"], correct: 1 },
  { q: "How many sides does a hexagon have?", choices: ["5", "6", "7", "8"], correct: 1 },
  { q: "What is the currency of the United Kingdom?", choices: ["Euro", "Dollar", "Pound sterling", "Franc"], correct: 2 },
  { q: "Which is the longest river in the world?", choices: ["Amazon", "Nile", "Yangtze", "Mississippi"], correct: 1 },
  { q: "Who developed the theory of general relativity?", choices: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Niels Bohr"], correct: 1 },
  { q: "What is the chemical symbol for water?", choices: ["CO2", "O2", "H2O", "NaCl"], correct: 2 },
  { q: "In which country would you find the Great Pyramid of Giza?", choices: ["Mexico", "Egypt", "Greece", "Iraq"], correct: 1 },
  { q: "What is the tallest mountain above sea level?", choices: ["K2", "Mount Everest", "Kilimanjaro", "Denali"], correct: 1 },
  { q: "How many strings does a standard guitar have?", choices: ["4", "5", "6", "7"], correct: 2 },
  { q: "Which language has the most native speakers worldwide?", choices: ["English", "Hindi", "Spanish", "Mandarin Chinese"], correct: 3 },
  { q: "What is the main ingredient in guacamole?", choices: ["Tomato", "Avocado", "Cucumber", "Pepper"], correct: 1 },
  { q: "What planet is closest to the Sun?", choices: ["Venus", "Earth", "Mercury", "Mars"], correct: 2 },
  { q: "Who is known as the 'Father of Computers'?", choices: ["Alan Turing", "Charles Babbage", "Bill Gates", "Steve Jobs"], correct: 1 },
  { q: "What is the freezing point of water in Celsius?", choices: ["-10°", "0°", "32°", "100°"], correct: 1 },
  { q: "Which artist is famous for the 'Starry Night' painting?", choices: ["Claude Monet", "Pablo Picasso", "Vincent van Gogh", "Salvador Dalí"], correct: 2 },
  { q: "How many bones are in the adult human body?", choices: ["186", "206", "226", "246"], correct: 1 },
  { q: "What is the largest organ in the human body?", choices: ["Liver", "Brain", "Skin", "Lungs"], correct: 2 },
  { q: "Which country gifted the Statue of Liberty to the USA?", choices: ["England", "France", "Spain", "Italy"], correct: 1 },
  { q: "What is the national flower of Japan?", choices: ["Rose", "Tulip", "Cherry blossom", "Lotus"], correct: 2 },
  { q: "Which gas makes up most of Earth's atmosphere?", choices: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], correct: 2 },
  { q: "What is the square root of 144?", choices: ["10", "11", "12", "14"], correct: 2 },
  { q: "Who wrote the play 'Hamlet'?", choices: ["Homer", "William Shakespeare", "Sophocles", "Oscar Wilde"], correct: 1 },
  { q: "What is the smallest country in the world?", choices: ["Monaco", "Vatican City", "Nauru", "San Marino"], correct: 1 },
  { q: "Which planet has the most moons?", choices: ["Jupiter", "Saturn", "Uranus", "Neptune"], correct: 1 },
  { q: "What instrument measures earthquakes?", choices: ["Barometer", "Seismograph", "Thermometer", "Hygrometer"], correct: 1 },
  { q: "How many colors are in a rainbow?", choices: ["5", "6", "7", "8"], correct: 2 },
  { q: "What is the capital of Canada?", choices: ["Toronto", "Vancouver", "Ottawa", "Montreal"], correct: 2 },
  { q: "Which metal is liquid at room temperature?", choices: ["Mercury", "Lead", "Iron", "Tin"], correct: 0 },
  { q: "What is the largest desert in the world?", choices: ["Sahara", "Gobi", "Antarctic Desert", "Arabian"], correct: 2 },
  { q: "Who composed the Ninth Symphony ('Ode to Joy')?", choices: ["Mozart", "Beethoven", "Bach", "Chopin"], correct: 1 },
  { q: "What does 'www' stand for?", choices: ["World Web Wide", "World Wide Web", "Web World Wide", "Wide World Web"], correct: 1 },
  { q: "Which sea creature has eight arms?", choices: ["Squid", "Octopus", "Jellyfish", "Starfish"], correct: 1 },
  { q: "What is the boiling point of water at sea level in Celsius?", choices: ["90°", "100°", "110°", "120°"], correct: 1 },
  { q: "Which country has the most time zones?", choices: ["Russia", "USA", "China", "France"], correct: 3 },
  { q: "What vitamin does the sun help your body produce?", choices: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], correct: 2 },
  { q: "What is the most abundant element in the universe?", choices: ["Oxygen", "Carbon", "Hydrogen", "Helium"], correct: 2 }
];

// "On this day" events keyed by MM-DD. A curated set of dates; days not
// present fall back to a deterministic pick from HISTORY_FALLBACK.
const HISTORY_BY_DATE = {
  "01-01": { year: 2000, text: "The Y2K rollover passed without the global computer catastrophe many had feared." },
  "01-15": { year: 2001, text: "Wikipedia, the free online encyclopedia, was launched." },
  "02-11": { year: 1990, text: "Nelson Mandela was released from prison after 27 years." },
  "02-14": { year: 1876, text: "Alexander Graham Bell filed his patent for the telephone." },
  "03-14": { year: 1879, text: "Albert Einstein was born in Ulm, Germany." },
  "04-12": { year: 1961, text: "Yuri Gagarin became the first human to journey into outer space." },
  "04-15": { year: 1452, text: "Leonardo da Vinci was born in Vinci, Italy." },
  "05-29": { year: 1953, text: "Edmund Hillary and Tenzing Norgay became the first to summit Mount Everest." },
  "06-06": { year: 1944, text: "D-Day: Allied forces landed on the beaches of Normandy in WWII." },
  "06-17": { year: 1885, text: "The Statue of Liberty arrived in New York Harbor aboard the French ship Isère." },
  "06-18": { year: 1815, text: "Napoleon was defeated at the Battle of Waterloo." },
  "07-04": { year: 1776, text: "The United States Declaration of Independence was adopted." },
  "07-20": { year: 1969, text: "Apollo 11 landed and Neil Armstrong walked on the Moon." },
  "08-06": { year: 1991, text: "Tim Berners-Lee published the first website, launching the World Wide Web." },
  "09-09": { year: 1947, text: "The first actual computer 'bug' — a moth — was logged at Harvard." },
  "10-04": { year: 1957, text: "The Soviet Union launched Sputnik 1, the first artificial satellite." },
  "11-09": { year: 1989, text: "The fall of the Berlin Wall began as crossings were opened." },
  "11-19": { year: 1863, text: "Abraham Lincoln delivered the Gettysburg Address." },
  "12-17": { year: 1903, text: "The Wright brothers made the first powered, controlled airplane flight." },
  "12-25": { year: 1990, text: "The first successful test of a connection to the World Wide Web took place." }
};

const HISTORY_FALLBACK = [
  { year: 1969, text: "Apollo 11 astronauts spent their first full day on the lunar surface." },
  { year: 1928, text: "Alexander Fleming discovered penicillin, revolutionizing medicine." },
  { year: 1492, text: "Christopher Columbus reached the Americas." },
  { year: 1903, text: "The first transcontinental automobile trip across the U.S. was completed." },
  { year: 1955, text: "Rosa Parks refused to give up her bus seat, sparking the Montgomery Bus Boycott." },
  { year: 1543, text: "Copernicus published his theory that the Earth revolves around the Sun." },
  { year: 1990, text: "The Hubble Space Telescope was deployed into orbit." },
  { year: 1815, text: "Mount Tambora erupted, the most powerful volcanic eruption in recorded history." },
  { year: 1989, text: "The first commercial dial-up internet connection became available." },
  { year: 1865, text: "The American Civil War came to an end." },
  { year: 1971, text: "Intel released the first commercially available microprocessor, the 4004." },
  { year: 1936, text: "The BBC began the world's first regular high-definition television service." },
  { year: 1859, text: "Charles Darwin published 'On the Origin of Species.'" },
  { year: 1977, text: "Voyager 1 and 2 launched on their grand tour of the outer solar system." },
  { year: 1947, text: "Chuck Yeager became the first person to break the sound barrier in level flight." },
  { year: 1981, text: "The first reusable spacecraft, Space Shuttle Columbia, launched." },
  { year: 1879, text: "Thomas Edison demonstrated a long-lasting incandescent light bulb." },
  { year: 1953, text: "Watson and Crick described the double-helix structure of DNA." },
  { year: 1991, text: "The Soviet Union was officially dissolved." },
  { year: 1804, text: "The Lewis and Clark Expedition set out to explore the American West." }
];
