// data.js — curated content pools for Daily.
// Daily items are chosen deterministically from the date so everyone
// sees the same content on a given day and it rotates every 24h.

// Facts skew hard toward technology, computer science, and art — including the
// places where those three collide, which tend to be the best ones.
const FUN_FACTS = [
  "The first computer program was written for a machine that was never built. Ada Lovelace published an algorithm for Babbage's Analytical Engine in 1843; the engine existed only on paper.",
  "Punch cards came from fashion. The Jacquard loom used them to weave patterned silk decades before Babbage borrowed the idea — programming was invented as a textile technology.",
  "The Antikythera mechanism is a 2,000-year-old analog computer with at least 30 bronze gears that predicted eclipses and planetary positions. Nothing of comparable complexity appears again for over a thousand years.",
  "Ray Tomlinson picked @ for email addresses in 1971 for a dull reason: it was the one symbol on the keyboard that never appeared in anyone's name.",
  "The Apollo Guidance Computer that landed humans on the Moon had about 4 KB of RAM. A single modern emoji, stored as color pixels, can be larger.",
  "Margaret Hamilton coined the term 'software engineering' partly to get her field taken seriously. A photo of her beside the printed Apollo source code shows a stack of paper taller than she is.",
  "Grace Hopper handed out pieces of wire 11.8 inches long — the distance light travels in one nanosecond — so engineers would stop asking why satellite signals were slow.",
  "The world's first webcam existed to check a coffee pot. Cambridge researchers pointed a camera at the Trojan Room percolator in 1991 so nobody would walk down three flights to find it empty.",
  "Wi-Fi doesn't stand for anything. A branding firm invented it as a catchier alternative to 'IEEE 802.11b Direct Sequence,' riffing on hi-fi.",
  "Space Invaders speeds up as you clear aliens because the 1978 hardware couldn't render many sprites quickly. The performance bug became the defining mechanic of the genre.",
  "Tony Hoare invented Quicksort in 1959 while working on machine translation of Russian. He couldn't figure out how to express it in the language he had, so he had to wait for ALGOL.",
  "Edsger Dijkstra designed his shortest-path algorithm in about 20 minutes at a café in Amsterdam in 1956, with no pencil and no paper. It now routes most of the internet's packets.",
  "David Huffman invented Huffman coding as a student because he'd rather write a term paper than take the final exam. It has compressed a large fraction of all digital data since.",
  "The Fast Fourier Transform was discovered by Gauss around 1805 and buried in his unpublished notes. It was independently rediscovered in 1965, roughly 160 years late.",
  "Claude Shannon's 1937 master's thesis — written at 21 — showed that electrical switching circuits could implement Boolean algebra. It's often called the most consequential master's thesis ever written.",
  "Shannon also built Theseus, a mechanical mouse that learned its way through a maze in 1950, plus a juggling machine and a flame-throwing trumpet.",
  "A Go board has roughly 2 × 10^170 legal positions. The observable universe contains around 10^80 atoms.",
  "Hedy Lamarr, one of the biggest film stars of the 1940s, co-invented frequency-hopping spread spectrum with avant-garde composer George Antheil. They synchronized the hops using player-piano rolls. It underpins Wi-Fi and Bluetooth.",
  "The QR code was inspired by a Go board. Denso Wave engineer Masahiro Hara was playing on his lunch break in 1994 when he realized black and white stones on a grid could encode data in two dimensions.",
  "Radia Perlman documented the spanning tree protocol — the thing that keeps Ethernet networks from melting down — as a poem, 'Algorhyme.'",
  "ENIAC's six original programmers were all women, and they were left uncredited for decades. Press photos of them at the machine were captioned as if they were models.",
  "The first PC virus, 'Brain' (1986), included the authors' real names, home address, and phone numbers in Lahore. They wrote it to track pirated copies of their medical software and got calls from all over the world.",
  "'Hello, world!' comes from Brian Kernighan's 1972 tutorial for the language B. He has said he doesn't remember why he chose it.",
  "Ctrl-Alt-Delete was a debugging shortcut by IBM engineer David Bradley. He put Delete on the far side of the keyboard specifically so you couldn't trigger it one-handed by accident.",
  "The word 'bug' predates computers by 70 years — Edison used it in an 1878 letter about faults in his machines. But the moth taped into the Harvard Mark II logbook in 1947 is the reason everyone remembers it.",
  "The Unix clock counts seconds from January 1, 1970. On a 32-bit signed integer it overflows on January 19, 2038, which is why that date has its own industry of remediation work.",
  "Douglas Engelbart's first mouse, built in 1964, was a hollowed block of wood with two perpendicular metal wheels. He never earned a cent from the patent — it expired before mice became common.",
  "The first .com domain was symbolics.com, registered in 1985. Only five more .com domains were registered that entire year.",
  "The first item ever sold on eBay was a broken laser pointer for $14.83. The founder emailed the buyer to check they understood it was broken; the buyer collected broken laser pointers.",
  "Amazon was almost named Cadabra, until a lawyer heard it over the phone as 'cadaver.'",
  "Google's original name was BackRub, because it analyzed the web's back links.",
  "JavaScript was prototyped in about ten days in May 1995. The 'Java' in the name was a marketing decision; the two languages are barely related.",
  "Python is named after Monty Python's Flying Circus, not the snake. Java was originally called Oak, after a tree outside the developer's window.",
  "Linus Torvalds wrote the first working version of Git in a couple of weeks, and it was managing its own source code within days.",
  "Pixar nearly lost Toy Story 2 to a stray delete command that wiped the film off the server in 1998. It survived because a technical director working from home after having a baby had been syncing a copy to her home machine.",
  "Rendering Toy Story took roughly 800,000 machine hours across a farm of 117 computers. A single frame could take more than a day.",
  "The most-rendered object in computer graphics is a teapot. Martin Newell digitized his own Melitta teapot in 1975 because he needed a test object with curves, a handle, and a hole; the real one now sits in a museum.",
  "Ken Perlin invented Perlin noise to make the effects in Tron (1982) look less synthetically perfect. It won him an Academy Award and it's why almost every digital cloud, flame, and mountain range looks the way it does.",
  "Bézier curves — behind every font you read and every vector graphic — were developed to design car bodies at Renault and Citroën in the 1960s.",
  "Auto-Tune came from oil prospecting. Andy Hildebrand adapted the signal processing he'd used to interpret seismic data into a way to detect and correct musical pitch.",
  "The MP3 format was tuned against Suzanne Vega's a cappella 'Tom's Diner.' Engineers played it thousands of times hunting for artifacts, which is why she's sometimes called the mother of the MP3.",
  "The first digital image was scanned in 1957: a 176 × 176 photograph of Russell Kirsch's infant son. He later said he regretted choosing square pixels.",
  "The original 176 emoji, designed by Shigetaka Kurita in 1999 on a 12 × 12 pixel grid for Japanese pagers, are now in the permanent collection of the Museum of Modern Art.",
  "Susan Kare designed the original Macintosh icons and fonts on graph paper, filling squares by hand before there was software to draw them in.",
  "The Mac's typography exists because Steve Jobs dropped out of college and sat in on a calligraphy class for fun. He credited it directly for proportional fonts on personal computers.",
  "Photoshop began as a side project: Thomas Knoll wrote it to display grayscale images on his Mac and called it 'Display.' His brother John, working at Industrial Light & Magic, realized what it was.",
  "Andy Warhol made digital art on an Amiga 1000 in 1985. The files sat unread on floppy disks until a group of computer club members and archivists recovered them in 2014.",
  "Harold Cohen spent over 40 years developing AARON, a program that made original paintings. He described the relationship less as using a tool than as collaborating with a colleague he had raised.",
  "Jackson Pollock's drip paintings contain measurable fractal structure, and their fractal dimension increased steadily over the years he worked in that style.",
  "reCAPTCHA quietly turned humans proving they weren't robots into a transcription workforce, digitizing millions of words from old books and newspaper archives.",
  "The Intel 4004, the first commercial microprocessor, had 2,300 transistors. Modern flagship chips carry more than 100 billion.",
  "The first gigabyte hard drive, IBM's 3380 in 1980, weighed about 550 pounds, was the size of a refrigerator, and cost around $40,000.",
  "The Voyager probes navigate interstellar space on roughly 70 kilobytes of memory — less than a single modern web page's worth of JavaScript.",
  "Tetris was written in 1984 by Alexey Pajitnov at a Soviet computing institute. The state owned the rights, and he earned essentially nothing from it for over a decade.",
  "Nintendo was founded in 1889 to make hanafuda playing cards, and Nokia began in 1865 as a paper mill.",
  "Ultramarine blue was once more expensive than gold. It came from lapis lazuli mined in a single region of Afghanistan, so Renaissance contracts specified exactly how much a painter was allowed to use.",
  "'Mummy brown' was a real pigment made from ground-up Egyptian mummies. Painters kept using it into the 20th century; some buried their tubes once they learned the ingredient.",
  "Yves Klein registered his own shade of blue. Anish Kapoor later secured exclusive artistic rights to Vantablack, prompting Stuart Semple to release 'the pinkest pink' that anyone on Earth could buy except Kapoor.",
  "The Mona Lisa was a relatively minor painting until it was stolen from the Louvre in 1911. Crowds lined up to stare at the empty wall, and it came back a global celebrity.",
  "Michelangelo painted the Sistine Chapel ceiling standing upright on scaffolding, craning backward — not lying on his back, as the story usually goes. He wrote a poem complaining about what it did to his neck.",
  "The oldest known figurative artwork is a warty pig painted on a cave wall in Sulawesi, Indonesia, at least 45,500 years ago.",
  "Someone pencilled 'Could only have been painted by a madman' onto Munch's The Scream. In 2021 the National Museum of Norway concluded the handwriting was Munch's own.",
  "Hokusai's Great Wave has no single original. It's a woodblock print, produced in thousands of impressions, and its striking blue came from Prussian blue pigment newly imported into Japan.",
  "The Bayeux Tapestry is not a tapestry — it's embroidery, roughly 70 meters of it, and it functions as a nearly 1,000-year-old comic strip.",
  "Banksy's Girl with Balloon shredded itself moments after selling at auction in 2018. Renamed Love Is in the Bin, the half-destroyed work resold three years later for about 18 times the price.",
  "Picasso's full baptismal name runs to over 20 words, chaining together saints and relatives.",
  "The Statue of Liberty was the color of a new penny when it arrived. It took about three decades of oxidation to turn green.",
  "The oldest known musical instruments are flutes carved from bird bone and mammoth ivory roughly 40,000 years ago — the same era as the first cave paintings.",
  "Comic Sans was drawn by Vincent Connare in 1994, based on comic book lettering, for a Microsoft help character that seemed absurd speaking in Times New Roman. It missed the deadline and shipped everywhere else instead.",
  "Vincent van Gogh sold almost nothing while alive and worked as a painter for barely a decade. He produced roughly 2,100 artworks in that time.",
  "The most expensive painting ever sold at auction, Salvator Mundi, went for $450.3 million in 2017 — and experts still argue about how much of it Leonardo actually painted."
];

const RIDDLES = [
  { q: "I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?", a: "An echo." },
  { q: "The more of me you take, the more you leave behind. What am I?", a: "Footsteps." },
  { q: "What has keys but can't open locks, space but no room, and you can enter but can't go inside?", a: "A keyboard." },
  { q: "I'm tall when I'm young and short when I'm old. What am I?", a: "A candle." },
  { q: "What has hands but cannot clap?", a: "A clock." },
  { q: "What gets wetter the more it dries?", a: "A towel." },
  { q: "I have cities but no houses, mountains but no trees, and water but no fish. What am I?", a: "A map." },
  { q: "What can travel around the world while staying in a corner?", a: "A stamp." },
  { q: "The person who makes it has no need of it. The person who buys it has no use for it. The person who uses it can't see or feel it. What is it?", a: "A coffin." },
  { q: "What has a head, a tail, but no body?", a: "A coin." },
  { q: "What has many teeth but cannot bite?", a: "A comb." },
  { q: "What can you catch but not throw?", a: "A cold." },
  { q: "I'm light as a feather, yet the strongest person can't hold me for more than a few minutes. What am I?", a: "Your breath." },
  { q: "What goes up but never comes down?", a: "Your age." },
  { q: "What has one eye but cannot see?", a: "A needle." },
  { q: "What gets bigger the more you take away from it?", a: "A hole." },
  { q: "What has a neck but no head?", a: "A bottle." },
  { q: "What runs but never walks, has a bed but never sleeps?", a: "A river." },
  { q: "What can fill a room but takes up no space?", a: "Light." },
  { q: "I have branches, but no fruit, trunk, or leaves. What am I?", a: "A bank." },
  { q: "What kind of band never plays music?", a: "A rubber band." },
  { q: "What has words but never speaks?", a: "A book." },
  { q: "Forward I'm heavy, but backward I'm not. What am I?", a: "The word 'ton.'" },
  { q: "What building has the most stories?", a: "A library." },
  { q: "If you drop me I'm sure to crack, but smile at me and I'll smile back. What am I?", a: "A mirror." },
  { q: "What has a thumb and four fingers but is not alive?", a: "A glove." },
  { q: "What invention lets you look right through a wall?", a: "A window." },
  { q: "What can you keep after giving it to someone?", a: "Your word." },
  { q: "I follow you all day long, but when the night comes I'm gone. What am I?", a: "Your shadow." },
  { q: "What has 13 hearts but no other organs?", a: "A deck of cards." }
];

const TRIVIA = [
  { q: "What is the largest planet in our solar system?", choices: ["Saturn", "Jupiter", "Neptune", "Earth"], correct: 1 },
  { q: "Which element has the chemical symbol 'Au'?", choices: ["Silver", "Aluminum", "Gold", "Argon"], correct: 2 },
  { q: "In what year did the first human land on the Moon?", choices: ["1965", "1969", "1972", "1959"], correct: 1 },
  { q: "What is the smallest prime number?", choices: ["0", "1", "2", "3"], correct: 2 },
  { q: "Which country is home to the kangaroo?", choices: ["Brazil", "South Africa", "Australia", "India"], correct: 2 },
  { q: "Who painted the Mona Lisa?", choices: ["Michelangelo", "Raphael", "Leonardo da Vinci", "Donatello"], correct: 2 },
  { q: "What is the hardest natural substance on Earth?", choices: ["Quartz", "Steel", "Diamond", "Titanium"], correct: 2 },
  { q: "How many continents are there on Earth?", choices: ["5", "6", "7", "8"], correct: 2 },
  { q: "What is the capital of Japan?", choices: ["Seoul", "Beijing", "Tokyo", "Bangkok"], correct: 2 },
  { q: "Which ocean is the largest?", choices: ["Atlantic", "Indian", "Arctic", "Pacific"], correct: 3 },
  { q: "What gas do plants primarily absorb from the atmosphere?", choices: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], correct: 2 },
  { q: "Who wrote 'Romeo and Juliet'?", choices: ["Charles Dickens", "William Shakespeare", "Mark Twain", "Jane Austen"], correct: 1 },
  { q: "What is the speed of light approximately?", choices: ["300,000 km/s", "30,000 km/s", "3,000 km/s", "3 million km/s"], correct: 0 },
  { q: "Which planet is known as the Red Planet?", choices: ["Venus", "Mars", "Mercury", "Jupiter"], correct: 1 },
  { q: "What is the largest mammal in the world?", choices: ["African elephant", "Blue whale", "Giraffe", "Hippopotamus"], correct: 1 },
  { q: "How many sides does a hexagon have?", choices: ["5", "6", "7", "8"], correct: 1 },
  { q: "What is the currency of the United Kingdom?", choices: ["Euro", "Dollar", "Pound sterling", "Franc"], correct: 2 },
  { q: "Which is the longest river in the world?", choices: ["Amazon", "Nile", "Yangtze", "Mississippi"], correct: 1 },
  { q: "Who developed the theory of general relativity?", choices: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Niels Bohr"], correct: 1 },
  { q: "What is the chemical symbol for water?", choices: ["CO2", "O2", "H2O", "NaCl"], correct: 2 },
  { q: "In which country would you find the Great Pyramid of Giza?", choices: ["Mexico", "Egypt", "Greece", "Iraq"], correct: 1 },
  { q: "What is the tallest mountain above sea level?", choices: ["K2", "Mount Everest", "Kilimanjaro", "Denali"], correct: 1 },
  { q: "How many strings does a standard guitar have?", choices: ["4", "5", "6", "7"], correct: 2 },
  { q: "Which language has the most native speakers worldwide?", choices: ["English", "Hindi", "Spanish", "Mandarin Chinese"], correct: 3 },
  { q: "What is the main ingredient in guacamole?", choices: ["Tomato", "Avocado", "Cucumber", "Pepper"], correct: 1 },
  { q: "What planet is closest to the Sun?", choices: ["Venus", "Earth", "Mercury", "Mars"], correct: 2 },
  { q: "Who is known as the 'Father of Computers'?", choices: ["Alan Turing", "Charles Babbage", "Bill Gates", "Steve Jobs"], correct: 1 },
  { q: "What is the freezing point of water in Celsius?", choices: ["-10°", "0°", "32°", "100°"], correct: 1 },
  { q: "Which artist is famous for the 'Starry Night' painting?", choices: ["Claude Monet", "Pablo Picasso", "Vincent van Gogh", "Salvador Dalí"], correct: 2 },
  { q: "How many bones are in the adult human body?", choices: ["186", "206", "226", "246"], correct: 1 },
  { q: "What is the largest organ in the human body?", choices: ["Liver", "Brain", "Skin", "Lungs"], correct: 2 },
  { q: "Which country gifted the Statue of Liberty to the USA?", choices: ["England", "France", "Spain", "Italy"], correct: 1 },
  { q: "What is the national flower of Japan?", choices: ["Rose", "Tulip", "Cherry blossom", "Lotus"], correct: 2 },
  { q: "Which gas makes up most of Earth's atmosphere?", choices: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], correct: 2 },
  { q: "What is the square root of 144?", choices: ["10", "11", "12", "14"], correct: 2 },
  { q: "Who wrote the play 'Hamlet'?", choices: ["Homer", "William Shakespeare", "Sophocles", "Oscar Wilde"], correct: 1 },
  { q: "What is the smallest country in the world?", choices: ["Monaco", "Vatican City", "Nauru", "San Marino"], correct: 1 },
  { q: "Which planet has the most moons?", choices: ["Jupiter", "Saturn", "Uranus", "Neptune"], correct: 1 },
  { q: "What instrument measures earthquakes?", choices: ["Barometer", "Seismograph", "Thermometer", "Hygrometer"], correct: 1 },
  { q: "How many colors are in a rainbow?", choices: ["5", "6", "7", "8"], correct: 2 },
  { q: "What is the capital of Canada?", choices: ["Toronto", "Vancouver", "Ottawa", "Montreal"], correct: 2 },
  { q: "Which metal is liquid at room temperature?", choices: ["Mercury", "Lead", "Iron", "Tin"], correct: 0 },
  { q: "What is the largest desert in the world?", choices: ["Sahara", "Gobi", "Antarctic Desert", "Arabian"], correct: 2 },
  { q: "Who composed the Ninth Symphony ('Ode to Joy')?", choices: ["Mozart", "Beethoven", "Bach", "Chopin"], correct: 1 },
  { q: "What does 'www' stand for?", choices: ["World Web Wide", "World Wide Web", "Web World Wide", "Wide World Web"], correct: 1 },
  { q: "Which sea creature has eight arms?", choices: ["Squid", "Octopus", "Jellyfish", "Starfish"], correct: 1 },
  { q: "What is the boiling point of water at sea level in Celsius?", choices: ["90°", "100°", "110°", "120°"], correct: 1 },
  { q: "Which country has the most time zones?", choices: ["Russia", "USA", "China", "France"], correct: 3 },
  { q: "What vitamin does the sun help your body produce?", choices: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], correct: 2 },
  { q: "What is the most abundant element in the universe?", choices: ["Oxygen", "Carbon", "Hydrogen", "Helium"], correct: 2 }
];

// "On this day" events keyed by MM-DD. A curated set of dates; days not
// present fall back to a deterministic pick from HISTORY_FALLBACK.
const HISTORY_BY_DATE = {
  "01-01": { year: 1983, text: "ARPANET switched over to TCP/IP in a single 'flag day' cutover — the moment the internet as we know it began speaking its native language." },
  "01-03": { year: 2009, text: "The Bitcoin genesis block was mined, with a Times headline about bank bailouts embedded in it as a timestamp and a comment." },
  "01-09": { year: 2007, text: "Steve Jobs introduced the iPhone at Macworld, demoing a device so unfinished the team had to follow an exact script to keep it from crashing on stage." },
  "01-15": { year: 2001, text: "Wikipedia launched — originally just a side experiment to feed articles into a more traditional, expert-reviewed encyclopedia project." },
  "01-24": { year: 1984, text: "The Macintosh went on sale, the first mass-market computer built around a mouse, windows, and proportional typefaces." },
  "01-28": { year: 1912, text: "Jackson Pollock was born. He would abandon the easel entirely, laying canvas on the floor and painting from above." },
  "02-04": { year: 2004, text: "Facebook launched from a Harvard dorm room, restricted at first to people with a harvard.edu email address." },
  "02-10": { year: 1996, text: "Deep Blue beat Garry Kasparov in a single game — the first time a computer defeated a reigning world champion under tournament conditions. Kasparov won the match anyway." },
  "02-14": { year: 1876, text: "Alexander Graham Bell filed his telephone patent, reportedly hours ahead of a rival filing on the same principle." },
  "02-16": { year: 1978, text: "The first computerized bulletin board system went online in Chicago, built during a blizzard. Online community predates the web by more than a decade." },
  "02-24": { year: 1955, text: "Steve Jobs was born. He later credited a college calligraphy class he audited for the Mac's typography." },
  "03-06": { year: 1475, text: "Michelangelo was born. He always described himself as a sculptor, and considered the Sistine Chapel ceiling a distraction from that." },
  "03-12": { year: 1989, text: "Tim Berners-Lee circulated a proposal at CERN for a hypertext system. His manager's note on the cover read: 'Vague but exciting.'" },
  "03-14": { year: 1879, text: "Albert Einstein was born — on what would later, by coincidence of notation, also become Pi Day." },
  "03-15": { year: 1985, text: "symbolics.com was registered, the first .com domain in existence. Only five more followed that year." },
  "03-21": { year: 2006, text: "The first tweet was posted: 'just setting up my twttr.' The 140-character limit existed to fit inside an SMS." },
  "03-30": { year: 1853, text: "Vincent van Gogh was born. He didn't start painting seriously until his late twenties and was dead within a decade." },
  "03-31": { year: 1889, text: "The Eiffel Tower opened. Leading French artists had signed a public letter calling it a monstrous, useless iron chimney." },
  "04-01": { year: 1976, text: "Apple Computer was founded. A third co-founder sold his 10% stake twelve days later for $800." },
  "04-03": { year: 1973, text: "Martin Cooper made the first handheld mobile phone call, standing on a Manhattan sidewalk — to his chief rival at Bell Labs, to tell him he'd done it first." },
  "04-04": { year: 1975, text: "Microsoft was founded to write a BASIC interpreter for a computer its founders had never actually seen in person." },
  "04-12": { year: 1961, text: "Yuri Gagarin became the first human in space, in a capsule flown almost entirely by automated control." },
  "04-15": { year: 1452, text: "Leonardo da Vinci was born. He wrote his notebooks in mirror script and left most of his projects unfinished." },
  "04-23": { year: 2005, text: "The first YouTube video was uploaded: 19 seconds of a co-founder standing in front of the elephants at the San Diego Zoo." },
  "04-30": { year: 1993, text: "CERN released the World Wide Web software into the public domain, royalty-free. Arguably the single most valuable thing anyone has ever given away." },
  "05-11": { year: 1904, text: "Salvador Dalí was born. He claimed to induce his melting imagery by napping in a chair holding a key over a metal plate." },
  "05-16": { year: 1929, text: "The first Academy Awards were handed out in a 15-minute ceremony. The winners had been announced three months earlier." },
  "05-17": { year: 1902, text: "An archaeologist noticed a gear embedded in a corroded lump from a Greek shipwreck — the Antikythera mechanism, a 2,000-year-old geared computer." },
  "05-22": { year: 1980, text: "Pac-Man was released in Japan, designed deliberately to appeal to players who had no interest in shooting things." },
  "05-24": { year: 1844, text: "Samuel Morse sent 'What hath God wrought' over the first long-distance telegraph line, collapsing the time it took news to cross a continent." },
  "05-25": { year: 1977, text: "Star Wars opened on fewer than 40 screens. The effects work behind it created the company that later became Pixar." },
  "05-29": { year: 1913, text: "The premiere of Stravinsky's The Rite of Spring in Paris set off a riot in the theater. It's now standard repertoire." },
  "06-01": { year: 1967, text: "Sgt. Pepper's Lonely Hearts Club Band was released, with a collaged cover so elaborate the band had to get legal clearance for the faces on it." },
  "06-08": { year: 1955, text: "Tim Berners-Lee was born. He would later refuse to patent the web." },
  "06-21": { year: 1948, text: "The Manchester 'Baby' ran the first program ever executed from electronic memory. It took 52 minutes to find the highest factor of a number." },
  "06-23": { year: 1912, text: "Alan Turing was born. His 1936 paper defined what a computer is before any computer existed." },
  "07-04": { year: 1997, text: "Mars Pathfinder landed and released Sojourner, the first rover to drive on another planet. It used airbags to bounce to a stop." },
  "07-06": { year: 1907, text: "Frida Kahlo was born. She painted most of her self-portraits using a mirror mounted above her bed." },
  "07-20": { year: 1969, text: "Apollo 11 landed while its guidance computer threw overflow alarms. The software had been designed to shed low-priority tasks instead of crashing — and that's why they didn't abort." },
  "08-01": { year: 1981, text: "MTV launched. The first video it played was 'Video Killed the Radio Star.'" },
  "08-06": { year: 1991, text: "Tim Berners-Lee posted a short public summary of the World Wide Web project to a Usenet newsgroup — the web's first public announcement." },
  "08-09": { year: 1995, text: "Netscape went public without ever having turned a profit, and the price more than doubled on day one. The dot-com era had a starting gun." },
  "08-12": { year: 1981, text: "IBM introduced the Personal Computer. Its open architecture let competitors clone it, which IBM had not adequately planned for." },
  "08-21": { year: 1911, text: "The Mona Lisa was stolen from the Louvre by a museum worker who simply walked out with it under his smock. The theft is what made it famous." },
  "09-04": { year: 1998, text: "Google was incorporated in a garage. Its founders had earlier tried to sell the technology for about $1 million and found no buyer." },
  "09-08": { year: 1504, text: "Michelangelo's David was unveiled in Florence, carved from a block of marble two other sculptors had already given up on." },
  "09-09": { year: 1947, text: "Operators pulled a moth out of the Harvard Mark II and taped it into the logbook: 'First actual case of bug being found.'" },
  "09-19": { year: 1982, text: "Scott Fahlman proposed :-) on a Carnegie Mellon message board to mark jokes. Every emoji descends from that suggestion." },
  "10-04": { year: 1957, text: "Sputnik 1 launched. The panic it caused in the U.S. led directly to the agency that funded ARPANET." },
  "10-05": { year: 2018, text: "Banksy's Girl with Balloon shredded itself seconds after selling at Sotheby's, via a mechanism hidden in the frame for years." },
  "10-23": { year: 2001, text: "Apple introduced the iPod. The press response was largely a shrug about an expensive music player with no wireless." },
  "10-25": { year: 1881, text: "Pablo Picasso was born. He was a fully trained academic realist by his teens and spent the rest of his life dismantling that training." },
  "10-28": { year: 1955, text: "Bill Gates was born. He wrote his first program, a tic-tac-toe game, at thirteen." },
  "10-29": { year: 1969, text: "The first message was sent over ARPANET. They typed 'LOGIN,' the system crashed after two characters, and the internet's first word was 'LO.'" },
  "10-30": { year: 1938, text: "Orson Welles broadcast The War of the Worlds as simulated news bulletins — an early demonstration that the format of a medium can be more persuasive than its content." },
  "11-01": { year: 1512, text: "The Sistine Chapel ceiling was revealed to the public after four years of work Michelangelo had tried to refuse." },
  "11-04": { year: 1922, text: "Howard Carter found the sealed entrance to Tutankhamun's tomb, preserving the largest intact collection of ancient Egyptian art ever recovered." },
  "11-09": { year: 1989, text: "The Berlin Wall opened. Within days, sections of it were being cut up and sold as art objects." },
  "11-18": { year: 1928, text: "Steamboat Willie premiered — not the first Mickey Mouse cartoon, but the first with synchronized sound, which is why it's the one everyone remembers." },
  "11-22": { year: 1995, text: "Toy Story opened, the first feature film animated entirely by computer. Every frame was rendered from scratch by a farm of machines running for months." },
  "11-30": { year: 2022, text: "ChatGPT was released as a low-key research preview. It reached a million users in five days." },
  "12-09": { year: 1968, text: "Douglas Engelbart's 'Mother of All Demos' showed the mouse, hypertext, windows, video conferencing, and collaborative editing — in one 90-minute session, decades before any of it shipped." },
  "12-10": { year: 1815, text: "Ada Lovelace was born. Her notes on Babbage's Analytical Engine include the first published algorithm intended for a machine." },
  "12-12": { year: 1913, text: "The Mona Lisa was recovered in Florence, two years after its theft, when the thief tried to sell it to an art dealer." },
  "12-16": { year: 1947, text: "Bell Labs built the first working transistor. Nearly every device you have ever used contains descendants of it, now measured in the billions per chip." },
  "12-17": { year: 1903, text: "The Wright brothers flew. The longest flight that day covered 852 feet — shorter than the wingspan of a modern airliner's route to the gate." },
  "12-21": { year: 1937, text: "Snow White premiered, the first full-length cel-animated feature. The industry had called it Disney's Folly." },
  "12-25": { year: 1990, text: "Tim Berners-Lee got the first web browser and web server talking to each other — the first successful client-server exchange over the World Wide Web." }
};

const HISTORY_FALLBACK = [
  { year: 1971, text: "Intel shipped the 4004, the first commercial microprocessor. It held 2,300 transistors and was designed for a desktop calculator." },
  { year: 1843, text: "Ada Lovelace published notes describing how a machine could manipulate symbols, not just numbers — the conceptual leap from calculator to computer." },
  { year: 1936, text: "Alan Turing described a machine that could simulate any other machine, defining the limits of computation before hardware existed to test it." },
  { year: 1948, text: "Claude Shannon published 'A Mathematical Theory of Communication,' inventing information theory and the bit in one paper." },
  { year: 1969, text: "Unix was started at Bell Labs as an unofficial project on a spare minicomputer nobody else wanted." },
  { year: 1973, text: "The Xerox Alto was built with a bitmapped screen, a mouse, and windows. Xerox never sold it, and visitors took the ideas elsewhere." },
  { year: 1977, text: "RSA public-key cryptography was published, making it possible to exchange secrets with strangers you've never met." },
  { year: 1984, text: "The first fully computer-generated character in a feature film appeared, stitched together frame by frame on machines slower than a modern thermostat." },
  { year: 1991, text: "Linux was announced as a hobby project that would 'not be big and professional like gnu.'" },
  { year: 1994, text: "The QR code was invented to track car parts on an assembly line, deliberately designed to still scan when partly damaged." },
  { year: 2007, text: "The smartphone era began in earnest, collapsing the camera, map, music player, and computer into one object." },
  { year: 1957, text: "The first digital image was scanned — a 176-pixel-square photograph, the ancestor of every JPEG." },
  { year: 1962, text: "Spacewar!, one of the first video games, was written for fun on a $120,000 research computer and given away for free." },
  { year: 1975, text: "A university researcher digitized a teapot as a graphics test object. It became the most rendered shape in the history of computing." },
  { year: 2021, text: "Researchers dated a warty pig painted on a cave wall in Sulawesi to at least 45,500 years ago — the oldest known figurative artwork anywhere." },
  { year: 1420, text: "Brunelleschi worked out linear perspective, giving European painting a mathematics of depth and changing how a flat surface could lie convincingly." },
  { year: 1665, text: "Vermeer painted Girl with a Pearl Earring — technically not a portrait but a tronie, a study of a type rather than a person." },
  { year: 1831, text: "Hokusai published The Great Wave, using a synthetic blue pigment newly imported from Europe." },
  { year: 1874, text: "The first Impressionist exhibition opened in Paris after the official Salon rejected the work. The movement's name came from a hostile review." },
  { year: 1907, text: "Picasso finished Les Demoiselles d'Avignon and showed it to almost no one for years. It broke the picture plane open and started Cubism." },
  { year: 1917, text: "Duchamp submitted a factory-made urinal to an exhibition as sculpture, and the question of what counts as art never fully closed again." },
  { year: 1962, text: "Pop Art arrived in the gallery, insisting that soup cans and comic panels were legitimate subjects for serious painting." },
  { year: 1968, text: "The exhibition Cybernetic Serendipity in London showed computer-generated art, music, and poetry to the public for the first time." },
  { year: 1985, text: "Desktop publishing arrived — a computer, a page layout program, and a laser printer put typesetting on a desk instead of in a print shop." }
];
