// data.js — curated content pools for Daily.
// Daily items are chosen deterministically from the date so everyone
// sees the same content on a given day and it rotates every 24h.

// Facts skew hard toward technology, computer science, and art — including the
// places where those three collide, which tend to be the best ones.
const FUN_FACTS = [
  "The first computer program was written for a machine that was never built. Ada Lovelace published an algorithm for Babbage's Analytical Engine in 1843; the engine existed only on paper.",
  "Punch cards came from fashion. The Jacquard loom used them to weave patterned silk decades before Babbage borrowed the idea — programming was invented as a textile technology.",
  "The Antikythera mechanism is a 2,000-year-old analog computer with at least 30 bronze gears that predicted eclipses and planetary positions. Nothing of comparable complexity appears again for over a thousand years.",
  "Ray Tomlinson picked @ for email addresses in 1971 for a dull reason: it was the one symbol on the keyboard that never appeared in anyone's name.",
  "The Apollo Guidance Computer that landed humans on the Moon had about 4 KB of RAM. A single modern emoji, stored as color pixels, can be larger.",
  "Margaret Hamilton coined the term 'software engineering' partly to get her field taken seriously. A photo of her beside the printed Apollo source code shows a stack of paper taller than she is.",
  "Grace Hopper handed out pieces of wire 11.8 inches long — the distance light travels in one nanosecond — so engineers would stop asking why satellite signals were slow.",
  "The world's first webcam existed to check a coffee pot. Cambridge researchers pointed a camera at the Trojan Room percolator in 1991 so nobody would walk down three flights to find it empty.",
  "Wi-Fi doesn't stand for anything. A branding firm invented it as a catchier alternative to 'IEEE 802.11b Direct Sequence,' riffing on hi-fi.",
  "Space Invaders speeds up as you clear aliens because the 1978 hardware couldn't render many sprites quickly. The performance bug became the defining mechanic of the genre.",
  "Tony Hoare invented Quicksort in 1959 while working on machine translation of Russian. He couldn't figure out how to express it in the language he had, so he had to wait for ALGOL.",
  "Edsger Dijkstra designed his shortest-path algorithm in about 20 minutes at a café in Amsterdam in 1956, with no pencil and no paper. It now routes most of the internet's packets.",
  "David Huffman invented Huffman coding as a student because he'd rather write a term paper than take the final exam. It has compressed a large fraction of all digital data since.",
  "The Fast Fourier Transform was discovered by Gauss around 1805 and buried in his unpublished notes. It was independently rediscovered in 1965, roughly 160 years late.",
  "Claude Shannon's 1937 master's thesis — written at 21 — showed that electrical switching circuits could implement Boolean algebra. It's often called the most consequential master's thesis ever written.",
  "Shannon also built Theseus, a mechanical mouse that learned its way through a maze in 1950, plus a juggling machine and a flame-throwing trumpet.",
  "A Go board has roughly 2 × 10^170 legal positions. The observable universe contains around 10^80 atoms.",
  "Hedy Lamarr, one of the biggest film stars of the 1940s, co-invented frequency-hopping spread spectrum with avant-garde composer George Antheil. They synchronized the hops using player-piano rolls. It underpins Wi-Fi and Bluetooth.",
  "The QR code was inspired by a Go board. Denso Wave engineer Masahiro Hara was playing on his lunch break in 1994 when he realized black and white stones on a grid could encode data in two dimensions.",
  "Radia Perlman documented the spanning tree protocol — the thing that keeps Ethernet networks from melting down — as a poem, 'Algorhyme.'",
  "ENIAC's six original programmers were all women, and they were left uncredited for decades. Press photos of them at the machine were captioned as if they were models.",
  "The first PC virus, 'Brain' (1986), included the authors' real names, home address, and phone numbers in Lahore. They wrote it to track pirated copies of their medical software and got calls from all over the world.",
  "'Hello, world!' comes from Brian Kernighan's 1972 tutorial for the language B. He has said he doesn't remember why he chose it.",
  "Ctrl-Alt-Delete was a debugging shortcut by IBM engineer David Bradley. He put Delete on the far side of the keyboard specifically so you couldn't trigger it one-handed by accident.",
  "The word 'bug' predates computers by 70 years — Edison used it in an 1878 letter about faults in his machines. But the moth taped into the Harvard Mark II logbook in 1947 is the reason everyone remembers it.",
  "The Unix clock counts seconds from January 1, 1970. On a 32-bit signed integer it overflows on January 19, 2038, which is why that date has its own industry of remediation work.",
  "Douglas Engelbart's first mouse, built in 1964, was a hollowed block of wood with two perpendicular metal wheels. He never earned a cent from the patent — it expired before mice became common.",
  "The first .com domain was symbolics.com, registered in 1985. Only five more .com domains were registered that entire year.",
  "The first item ever sold on eBay was a broken laser pointer for $14.83. The founder emailed the buyer to check they understood it was broken; the buyer collected broken laser pointers.",
  "Amazon was almost named Cadabra, until a lawyer heard it over the phone as 'cadaver.'",
  "Google's original name was BackRub, because it analyzed the web's back links.",
  "JavaScript was prototyped in about ten days in May 1995. The 'Java' in the name was a marketing decision; the two languages are barely related.",
  "Python is named after Monty Python's Flying Circus, not the snake. Java was originally called Oak, after a tree outside the developer's window.",
  "Linus Torvalds wrote the first working version of Git in a couple of weeks, and it was managing its own source code within days.",
  "Pixar nearly lost Toy Story 2 to a stray delete command that wiped the film off the server in 1998. It survived because a technical director working from home after having a baby had been syncing a copy to her home machine.",
  "Rendering Toy Story took roughly 800,000 machine hours across a farm of 117 computers. A single frame could take more than a day.",
  "The most-rendered object in computer graphics is a teapot. Martin Newell digitized his own Melitta teapot in 1975 because he needed a test object with curves, a handle, and a hole; the real one now sits in a museum.",
  "Ken Perlin invented Perlin noise to make the effects in Tron (1982) look less synthetically perfect. It won him an Academy Award and it's why almost every digital cloud, flame, and mountain range looks the way it does.",
  "Bézier curves — behind every font you read and every vector graphic — were developed to design car bodies at Renault and Citroën in the 1960s.",
  "Auto-Tune came from oil prospecting. Andy Hildebrand adapted the signal processing he'd used to interpret seismic data into a way to detect and correct musical pitch.",
  "The MP3 format was tuned against Suzanne Vega's a cappella 'Tom's Diner.' Engineers played it thousands of times hunting for artifacts, which is why she's sometimes called the mother of the MP3.",
  "The first digital image was scanned in 1957: a 176 × 176 photograph of Russell Kirsch's infant son. He later said he regretted choosing square pixels.",
  "The original 176 emoji, designed by Shigetaka Kurita in 1999 on a 12 × 12 pixel grid for Japanese pagers, are now in the permanent collection of the Museum of Modern Art.",
  "Susan Kare designed the original Macintosh icons and fonts on graph paper, filling squares by hand before there was software to draw them in.",
  "The Mac's typography exists because Steve Jobs dropped out of college and sat in on a calligraphy class for fun. He credited it directly for proportional fonts on personal computers.",
  "Photoshop began as a side project: Thomas Knoll wrote it to display grayscale images on his Mac and called it 'Display.' His brother John, working at Industrial Light & Magic, realized what it was.",
  "Andy Warhol made digital art on an Amiga 1000 in 1985. The files sat unread on floppy disks until a group of computer club members and archivists recovered them in 2014.",
  "Harold Cohen spent over 40 years developing AARON, a program that made original paintings. He described the relationship less as using a tool than as collaborating with a colleague he had raised.",
  "Jackson Pollock's drip paintings contain measurable fractal structure, and their fractal dimension increased steadily over the years he worked in that style.",
  "reCAPTCHA quietly turned humans proving they weren't robots into a transcription workforce, digitizing millions of words from old books and newspaper archives.",
  "The Intel 4004, the first commercial microprocessor, had 2,300 transistors. Modern flagship chips carry more than 100 billion.",
  "The first gigabyte hard drive, IBM's 3380 in 1980, weighed about 550 pounds, was the size of a refrigerator, and cost around $40,000.",
  "The Voyager probes navigate interstellar space on roughly 70 kilobytes of memory — less than a single modern web page's worth of JavaScript.",
  "Tetris was written in 1984 by Alexey Pajitnov at a Soviet computing institute. The state owned the rights, and he earned essentially nothing from it for over a decade.",
  "Nintendo was founded in 1889 to make hanafuda playing cards, and Nokia began in 1865 as a paper mill.",
  "Ultramarine blue was once more expensive than gold. It came from lapis lazuli mined in a single region of Afghanistan, so Renaissance contracts specified exactly how much a painter was allowed to use.",
  "'Mummy brown' was a real pigment made from ground-up Egyptian mummies. Painters kept using it into the 20th century; some buried their tubes once they learned the ingredient.",
  "Yves Klein registered his own shade of blue. Anish Kapoor later secured exclusive artistic rights to Vantablack, prompting Stuart Semple to release 'the pinkest pink' that anyone on Earth could buy except Kapoor.",
  "The Mona Lisa was a relatively minor painting until it was stolen from the Louvre in 1911. Crowds lined up to stare at the empty wall, and it came back a global celebrity.",
  "Michelangelo painted the Sistine Chapel ceiling standing upright on scaffolding, craning backward — not lying on his back, as the story usually goes. He wrote a poem complaining about what it did to his neck.",
  "The oldest known figurative artwork is a warty pig painted on a cave wall in Sulawesi, Indonesia, at least 45,500 years ago.",
  "Someone pencilled 'Could only have been painted by a madman' onto Munch's The Scream. In 2021 the National Museum of Norway concluded the handwriting was Munch's own.",
  "Hokusai's Great Wave has no single original. It's a woodblock print, produced in thousands of impressions, and its striking blue came from Prussian blue pigment newly imported into Japan.",
  "The Bayeux Tapestry is not a tapestry — it's embroidery, roughly 70 meters of it, and it functions as a nearly 1,000-year-old comic strip.",
  "Banksy's Girl with Balloon shredded itself moments after selling at auction in 2018. Renamed Love Is in the Bin, the half-destroyed work resold three years later for about 18 times the price.",
  "Picasso's full baptismal name runs to over 20 words, chaining together saints and relatives.",
  "The Statue of Liberty was the color of a new penny when it arrived. It took about three decades of oxidation to turn green.",
  "The oldest known musical instruments are flutes carved from bird bone and mammoth ivory roughly 40,000 years ago — the same era as the first cave paintings.",
  "Comic Sans was drawn by Vincent Connare in 1994, based on comic book lettering, for a Microsoft help character that seemed absurd speaking in Times New Roman. It missed the deadline and shipped everywhere else instead.",
  "Vincent van Gogh sold almost nothing while alive and worked as a painter for barely a decade. He produced roughly 2,100 artworks in that time.",
  "The most expensive painting ever sold at auction, Salvator Mundi, went for $450.3 million in 2017 — and experts still argue about how much of it Leonardo actually painted."
];

const RIDDLES = [
  { q: "I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?", a: "An echo." },
  { q: "The more of me you take, the more you leave behind. What am I?", a: "Footsteps." },
  { q: "What has keys but can't open locks, space but no room, and you can enter but can't go inside?", a: "A keyboard." },
  { q: "I'm tall when I'm young and short when I'm old. What am I?", a: "A candle." },
  { q: "What has hands but cannot clap?", a: "A clock." },
  { q: "What gets wetter the more it dries?", a: "A towel." },
  { q: "I have cities but no houses, mountains but no trees, and water but no fish. What am I?", a: "A map." },
  { q: "What can travel around the world while staying in a corner?", a: "A stamp." },
  { q: "The person who makes it has no need of it. The person who buys it has no use for it. The person who uses it can't see or feel it. What is it?", a: "A coffin." },
  { q: "What has a head, a tail, but no body?", a: "A coin." },
  { q: "What has many teeth but cannot bite?", a: "A comb." },
  { q: "What can you catch but not throw?", a: "A cold." },
  { q: "I'm light as a feather, yet the strongest person can't hold me for more than a few minutes. What am I?", a: "Your breath." },
  { q: "What goes up but never comes down?", a: "Your age." },
  { q: "What has one eye but cannot see?", a: "A needle." },
  { q: "What gets bigger the more you take away from it?", a: "A hole." },
  { q: "What has a neck but no head?", a: "A bottle." },
  { q: "What runs but never walks, has a bed but never sleeps?", a: "A river." },
  { q: "What can fill a room but takes up no space?", a: "Light." },
  { q: "I have branches, but no fruit, trunk, or leaves. What am I?", a: "A bank." },
  { q: "What kind of band never plays music?", a: "A rubber band." },
  { q: "What has words but never speaks?", a: "A book." },
  { q: "Forward I'm heavy, but backward I'm not. What am I?", a: "The word 'ton.'" },
  { q: "What building has the most stories?", a: "A library." },
  { q: "If you drop me I'm sure to crack, but smile at me and I'll smile back. What am I?", a: "A mirror." },
  { q: "What has a thumb and four fingers but is not alive?", a: "A glove." },
  { q: "What invention lets you look right through a wall?", a: "A window." },
  { q: "What can you keep after giving it to someone?", a: "Your word." },
  { q: "I follow you all day long, but when the night comes I'm gone. What am I?", a: "Your shadow." },
  { q: "What has 13 hearts but no other organs?", a: "A deck of cards." }
];

const TRIVIA = [
  { q: "What is the largest planet in our solar system?", choices: ["Saturn", "Jupiter", "Neptune", "Earth"], correct: 1 },
  { q: "Which element has the chemical symbol 'Au'?", choices: ["Silver", "Aluminum", "Gold", "Argon"], correct: 2 },
  { q: "In what year did the first human land on the Moon?", choices: ["1965", "1969", "1972", "1959"], correct: 1 },
  { q: "What is the smallest prime number?", choices: ["0", "1", "2", "3"], correct: 2 },
  { q: "Which country is home to the kangaroo?", choices: ["Brazil", "South Africa", "Australia", "India"], correct: 2 },
  { q: "Who painted the Mona Lisa?", choices: ["Michelangelo", "Raphael", "Leonardo da Vinci", "Donatello"], correct: 2 },
  { q: "What is the hardest natural substance on Earth?", choices: ["Quartz", "Steel", "Diamond", "Titanium"], correct: 2 },
  { q: "How many continents are there on Earth?", choices: ["5", "6", "7", "8"], correct: 2 },
  { q: "What is the capital of Japan?", choices: ["Seoul", "Beijing", "Tokyo", "Bangkok"], correct: 2 },
  { q: "Which ocean is the largest?", choices: ["Atlantic", "Indian", "Arctic", "Pacific"], correct: 3 },
  { q: "What gas do plants primarily absorb from the atmosphere?", choices: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], correct: 2 },
  { q: "Who wrote 'Romeo and Juliet'?", choices: ["Charles Dickens", "William Shakespeare", "Mark Twain", "Jane Austen"], correct: 1 },
  { q: "What is the speed of light approximately?", choices: ["300,000 km/s", "30,000 km/s", "3,000 km/s", "3 million km/s"], correct: 0 },
  { q: "Which planet is known as the Red Planet?", choices: ["Venus", "Mars", "Mercury", "Jupiter"], correct: 1 },
  { q: "What is the largest mammal in the world?", choices: ["African elephant", "Blue whale", "Giraffe", "Hippopotamus"], correct: 1 },
  { q: "How many sides does a hexagon have?", choices: ["5", "6", "7", "8"], correct: 1 },
  { q: "What is the currency of the United Kingdom?", choices: ["Euro", "Dollar", "Pound sterling", "Franc"], correct: 2 },
  { q: "Which is the longest river in the world?", choices: ["Amazon", "Nile", "Yangtze", "Mississippi"], correct: 1 },
  { q: "Who developed the theory of general relativity?", choices: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Niels Bohr"], correct: 1 },
  { q: "What is the chemical symbol for water?", choices: ["CO2", "O2", "H2O", "NaCl"], correct: 2 },
  { q: "In which country would you find the Great Pyramid of Giza?", choices: ["Mexico", "Egypt", "Greece", "Iraq"], correct: 1 },
  { q: "What is the tallest mountain above sea level?", choices: ["K2", "Mount Everest", "Kilimanjaro", "Denali"], correct: 1 },
  { q: "How many strings does a standard guitar have?", choices: ["4", "5", "6", "7"], correct: 2 },
  { q: "Which language has the most native speakers worldwide?", choices: ["English", "Hindi", "Spanish", "Mandarin Chinese"], correct: 3 },
  { q: "What is the main ingredient in guacamole?", choices: ["Tomato", "Avocado", "Cucumber", "Pepper"], correct: 1 },
  { q: "What planet is closest to the Sun?", choices: ["Venus", "Earth", "Mercury", "Mars"], correct: 2 },
  { q: "Who is known as the 'Father of Computers'?", choices: ["Alan Turing", "Charles Babbage", "Bill Gates", "Steve Jobs"], correct: 1 },
  { q: "What is the freezing point of water in Celsius?", choices: ["-10°", "0°", "32°", "100°"], correct: 1 },
  { q: "Which artist is famous for the 'Starry Night' painting?", choices: ["Claude Monet", "Pablo Picasso", "Vincent van Gogh", "Salvador Dalí"], correct: 2 },
  { q: "How many bones are in the adult human body?", choices: ["186", "206", "226", "246"], correct: 1 },
  { q: "What is the largest organ in the human body?", choices: ["Liver", "Brain", "Skin", "Lungs"], correct: 2 },
  { q: "Which country gifted the Statue of Liberty to the USA?", choices: ["England", "France", "Spain", "Italy"], correct: 1 },
  { q: "What is the national flower of Japan?", choices: ["Rose", "Tulip", "Cherry blossom", "Lotus"], correct: 2 },
  { q: "Which gas makes up most of Earth's atmosphere?", choices: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], correct: 2 },
  { q: "What is the square root of 144?", choices: ["10", "11", "12", "14"], correct: 2 },
  { q: "Who wrote the play 'Hamlet'?", choices: ["Homer", "William Shakespeare", "Sophocles", "Oscar Wilde"], correct: 1 },
  { q: "What is the smallest country in the world?", choices: ["Monaco", "Vatican City", "Nauru", "San Marino"], correct: 1 },
  { q: "Which planet has the most moons?", choices: ["Jupiter", "Saturn", "Uranus", "Neptune"], correct: 1 },
  { q: "What instrument measures earthquakes?", choices: ["Barometer", "Seismograph", "Thermometer", "Hygrometer"], correct: 1 },
  { q: "How many colors are in a rainbow?", choices: ["5", "6", "7", "8"], correct: 2 },
  { q: "What is the capital of Canada?", choices: ["Toronto", "Vancouver", "Ottawa", "Montreal"], correct: 2 },
  { q: "Which metal is liquid at room temperature?", choices: ["Mercury", "Lead", "Iron", "Tin"], correct: 0 },
  { q: "What is the largest desert in the world?", choices: ["Sahara", "Gobi", "Antarctic Desert", "Arabian"], correct: 2 },
  { q: "Who composed the Ninth Symphony ('Ode to Joy')?", choices: ["Mozart", "Beethoven", "Bach", "Chopin"], correct: 1 },
  { q: "What does 'www' stand for?", choices: ["World Web Wide", "World Wide Web", "Web World Wide", "Wide World Web"], correct: 1 },
  { q: "Which sea creature has eight arms?", choices: ["Squid", "Octopus", "Jellyfish", "Starfish"], correct: 1 },
  { q: "What is the boiling point of water at sea level in Celsius?", choices: ["90°", "100°", "110°", "120°"], correct: 1 },
  { q: "Which country has the most time zones?", choices: ["Russia", "USA", "China", "France"], correct: 3 },
  { q: "What vitamin does the sun help your body produce?", choices: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], correct: 2 },
  { q: "What is the most abundant element in the universe?", choices: ["Oxygen", "Carbon", "Hydrogen", "Helium"], correct: 2 }
];

// Artwork of the day. Each entry carries its catalogue details, a blurb
// explaining what makes it worth a minute of attention, and the parameters
// artwork.js needs to draw a study of it — a generated abstraction built from
// the work's own palette and composition, never a reproduction of the original.
//
// wiki       English Wikipedia article title, used to look up a photograph of
//            the real work at runtime (see artwork.js). Only freely licensed
//            Commons files are ever displayed; works still in copyright fall
//            back to the generated study.
// style      which renderer in artwork.js draws the study, used as the
//            placeholder while the photograph loads and as the fallback
// palette    colours sampled from the work itself; palette[0] is the ground
// faithful   true when the work is geometric/algorithmic enough that the study
//            genuinely reconstructs its logic rather than merely evoking it
const ARTWORKS = [
  {
    title: "Schotter (Gravel)",
    artist: "Georg Nees",
    year: "1968",
    medium: "Computer-generated drawing, lithograph on paper",
    where: "Victoria and Albert Museum, London",
    blurb: "A grid of squares that falls apart as it descends. Nees wrote an ALGOL program, plotted on a Zuse Graphomat, that drew each square with a small random rotation and offset, then let that randomness grow row by row, so order at the top decays into rubble at the bottom. It is one of the first artworks whose composition was authored as an algorithm rather than drawn, and it still teaches the central lesson of generative art: the artist chooses the rule, and the rule chooses the picture.",
    style: "scatter",
    faithful: true,
    palette: ["#f3efe6", "#1a1a1a"]
  },
  {
    title: "Interruptions",
    artist: "Vera Molnár",
    year: "1968–69",
    medium: "Plotter drawing on paper",
    where: "The Morgan Library & Museum, New York, and other collections",
    blurb: "A dense field of short line segments, each rotated slightly at random — and then Molnár deletes patches of them, leaving holes the eye reads as shapes that aren't there. She had been making 'machine imaginaire' work for years before she had a computer, simulating algorithms by hand. When she finally got access to one in 1968 she taught herself Fortran, punched her program onto cards, and was already in her forties.",
    style: "interruptions",
    faithful: true,
    palette: ["#f5f2ea", "#151515"]
  },
  {
    title: "Andy2",
    artist: "Andy Warhol",
    year: "1985",
    medium: "Digital image on floppy disk",
    where: "The Andy Warhol Museum, Pittsburgh",
    blurb: "Commodore paid Warhol to demo the new Amiga 1000 on stage, and he kept experimenting with it afterwards, filling flood-tool colour into portraits and Venus heads. The files then sat unread on floppies for nearly thirty years, until a computer club and a group of archivists rebuilt enough of the format to open them in 2014. It is one of the only cases where recovering an artist's work required reverse engineering a dead file system.",
    style: "pixel",
    faithful: false,
    palette: ["#1d1440", "#ff4fa3", "#28d9d0", "#ffd23f", "#f6f2ff"]
  },
  {
    title: "Portrait of Edmond de Belamy",
    wiki: "Edmond de Belamy",
    artist: "Obvious (with a GAN)",
    year: "2018",
    medium: "Inkjet print on canvas",
    where: "Private collection",
    blurb: "The first artwork generated by a neural network to be sold at a major auction house — it went for $432,500, roughly forty times its estimate. Its signature is the loss function of the generative adversarial network that made it, printed as a line of mathematics. The controversy afterwards was instructive: much of the underlying code had been written and released by a teenager, Robbie Barrat, raising a question the art market had never had to answer about who exactly the artist is.",
    style: "figure",
    faithful: false,
    palette: ["#3a3020", "#141008", "#c9a227", "#e8ddc0", "#8a6f3a"]
  },
  {
    title: "Electronic Superhighway: Continental U.S., Alaska, Hawaii",
    wiki: "Electronic Superhighway: Continental U.S., Alaska, Hawaii",
    artist: "Nam June Paik",
    year: "1995",
    medium: "Neon, video, and 336 television screens",
    where: "Smithsonian American Art Museum, Washington, D.C.",
    blurb: "A map of the United States built from neon outlines and hundreds of live CRT screens, each state playing its own loop of footage. Paik had coined the phrase 'electronic superhighway' back in 1974, roughly two decades before the internet became a household idea, and he meant it as a warning as much as a prophecy. Standing in front of it, you can't watch any one screen without losing all the others — which was largely the point.",
    style: "repeat",
    faithful: false,
    palette: ["#080814", "#ff2d95", "#00e5ff", "#39ff88", "#ffe14d"]
  },
  {
    title: "A Sunday on La Grande Jatte",
    wiki: "A Sunday Afternoon on the Island of La Grande Jatte",
    artist: "Georges Seurat",
    year: "1884–86",
    medium: "Oil on canvas",
    where: "Art Institute of Chicago",
    blurb: "Seurat built this scene out of some 220,000 separate dots of unmixed colour, on the theory that the eye would blend them more vividly than a palette could. He was essentially hand-computing additive colour mixing decades before anyone had a screen to do it on — a pixel grid painted by a person, at a rate of about one two-metre canvas every two years.",
    style: "dots",
    faithful: false,
    palette: ["#2f5d34", "#7fae4e", "#d8c96b", "#3d6fa8", "#e6dfae"]
  },
  {
    title: "Rain, Steam and Speed – The Great Western Railway",
    wiki: "Rain, Steam and Speed – The Great Western Railway",
    artist: "J. M. W. Turner",
    year: "1844",
    medium: "Oil on canvas",
    where: "National Gallery, London",
    blurb: "A locomotive comes at you out of a storm, and almost everything else in the picture has dissolved into weather. Turner painted it when railways were the disruptive technology of the age, and rather than depicting the machine he painted what it felt like to be overtaken by one. He put a hare on the track ahead of the engine, running to stay in front of it — and one witness said the hare, not the train, was the thing meant to stand for speed. The paint has since gone transparent and the hare is now almost impossible to see.",
    style: "swirl",
    faithful: false,
    palette: ["#8a7d5c", "#d9c99a", "#f0e6c8", "#5c4a2e", "#2b2418"]
  },
  {
    title: "Relativity",
    wiki: "Relativity (M. C. Escher)",
    artist: "M. C. Escher",
    year: "1953",
    medium: "Lithograph (a woodcut version came first)",
    where: "Editions in various collections",
    blurb: "Three sources of gravity coexist in one building, so a staircase that is a floor to one figure is a wall to another. Escher had no mathematical training and worked it out visually, yet mathematicians and computer scientists adopted him immediately — the print is a rigorous demonstration that a scene can be locally consistent everywhere and globally impossible, which is exactly the failure mode that haunts 3D geometry code.",
    style: "grid",
    faithful: false,
    palette: ["#d9d3c4", "#3a3730", "#8e8778", "#f2eee3", "#1b1a16"]
  },
  {
    title: "The Treachery of Images",
    wiki: "The Treachery of Images",
    artist: "René Magritte",
    year: "1929",
    medium: "Oil on canvas",
    where: "Los Angeles County Museum of Art",
    blurb: "A carefully painted pipe, captioned 'Ceci n'est pas une pipe' — this is not a pipe. Magritte's defence was unanswerable: try filling it with tobacco. The painting is about the gap between a thing and its representation, which is the same gap every map, model, dataset, and user interface lives inside.",
    style: "mono",
    faithful: false,
    palette: ["#c7a86a", "#3b2a1a", "#e6d5ac", "#1d150c"]
  },
  {
    title: "Broadway Boogie Woogie",
    wiki: "Broadway Boogie Woogie",
    artist: "Piet Mondrian",
    year: "1942–43",
    medium: "Oil on canvas",
    where: "Museum of Modern Art, New York",
    blurb: "Mondrian's last completed painting, made after he fled the war for New York and fell hard for the city and its jazz. He dropped the black rules that had defined his work for twenty years and replaced them with lines built from small coloured blocks, so the grid itself pulses. People have compared it to a circuit board and a street map ever since, and neither reading is wrong.",
    style: "pixel",
    faithful: true,
    palette: ["#f2f0e4", "#f2c400", "#d3132b", "#1d55a8", "#e8e6da"]
  },
  {
    title: "Movement in Squares",
    artist: "Bridget Riley",
    year: "1961",
    medium: "Tempera on hardboard",
    where: "Arts Council Collection, UK",
    blurb: "A checkerboard that compresses toward the centre until the surface appears to fold away from you. Riley works in black and white here with no illusionistic tricks at all — the buckling happens entirely in your visual system, which is the subject of the work. She spent decades insisting that Op art was about perception rather than optical gimmickry, while the fashion industry printed it on dresses anyway.",
    style: "opwave",
    faithful: true,
    palette: ["#f6f6f4", "#141414"]
  },
  {
    title: "Homage to the Square",
    wiki: "Homage to the Square",
    artist: "Josef Albers",
    year: "1950–76",
    medium: "Oil on masonite",
    where: "Series held in collections worldwide",
    blurb: "Albers painted more than a thousand versions of the same arrangement — three or four nested squares, always offset downward — for the last twenty-six years of his life. The point was never the square. It was that a colour has no fixed identity: the same pigment reads warm against one neighbour and cold against another, which he documented so rigorously that his book Interaction of Color is still assigned to designers today.",
    style: "concentric",
    faithful: true,
    palette: ["#c9502a", "#e08b3c", "#efc75e", "#f7e7b4"]
  },
  {
    title: "Composition with Red, Blue and Yellow",
    wiki: "Composition with Red, Blue and Yellow",
    artist: "Piet Mondrian",
    year: "1930",
    medium: "Oil on canvas",
    where: "Kunsthaus Zürich",
    blurb: "Black rules, white ground, three primaries, no diagonals and no curves — a whole visual language reduced to its axioms. Mondrian arrived here by painting trees over and over until the branches straightened into a lattice. Look closely at the originals and the black lines are visibly hand-brushed and slightly uneven, which is the part reproductions always lose.",
    style: "grid",
    faithful: true,
    palette: ["#f4f2e9", "#111111", "#d0021b", "#0b4ea2", "#f5c518"]
  },
  {
    title: "No. 61 (Rust and Blue)",
    wiki: "No. 61 (Rust and Blue)",
    artist: "Mark Rothko",
    year: "1953",
    medium: "Oil on canvas",
    where: "Museum of Contemporary Art, Los Angeles",
    blurb: "Two soft-edged blocks of colour hovering on a ground, at a scale meant to be viewed from about eighteen inches away. Rothko was furious at being called an abstractionist or a colourist; he said he was interested in tragedy, ecstasy and doom, and that people who wept in front of his paintings were having the same religious experience he had while making them.",
    style: "fields",
    faithful: true,
    palette: ["#5b1f14", "#8c3a1e", "#2e3f6e", "#1a1a24"]
  },
  {
    title: "Black Square",
    wiki: "Black Square (painting)",
    artist: "Kazimir Malevich",
    year: "1915",
    medium: "Oil on canvas",
    where: "Tretyakov Gallery, Moscow",
    blurb: "Malevich hung it high in the corner of the room, the position a Russian household reserves for its icon, and called it the zero point of painting. X-rays later revealed two earlier compositions underneath, plus a faint inscription. The paint has since cracked into a web of craquelure, so the emptiest painting in modern art now has a great deal of texture in it.",
    style: "mono",
    faithful: true,
    palette: ["#efece2", "#0d0d0d", "#d8d4c6"]
  },
  {
    title: "IKB 191",
    wiki: "International Klein Blue",
    artist: "Yves Klein",
    year: "1962",
    medium: "Dry pigment in synthetic resin on canvas",
    where: "Private collection",
    blurb: "A rectangle of one colour, and the colour is the entire work. Klein spent years developing a binder that would hold raw ultramarine pigment without dulling it, then registered the recipe as International Klein Blue. He also sold 'zones of immaterial pictorial sensibility' for gold, half of which he threw into the Seine while the buyer burned the receipt.",
    style: "mono",
    faithful: true,
    palette: ["#1b1c8c", "#2323b5", "#101070"]
  },
  {
    title: "Fountain",
    wiki: "Fountain (Duchamp)",
    artist: "Marcel Duchamp",
    year: "1917",
    medium: "Porcelain urinal",
    where: "Original lost; replicas in major collections",
    blurb: "Duchamp bought a urinal, turned it on its back, signed it 'R. Mutt' and submitted it to an exhibition that had promised to accept everything. The committee — which included Duchamp, anonymously — rejected it anyway. The original disappeared almost immediately, so every Fountain you can visit is a later replica, which means the most famous sculpture of the twentieth century survives mainly as an idea plus a photograph.",
    style: "mono",
    faithful: false,
    palette: ["#d9d6cd", "#f4f2ec", "#8f8b80", "#2b2a26"]
  },
  {
    title: "Whaam!",
    wiki: "Whaam!",
    artist: "Roy Lichtenstein",
    year: "1963",
    medium: "Acrylic and oil on canvas",
    where: "Tate Modern, London",
    blurb: "Two panels, six feet each, enlarging a single frame from a 1962 war comic into hand-painted Ben-Day dots. Lichtenstein was taking the cheapest available printing artefact — the halftone dot used to fake shading on newsprint — and rendering it laboriously by hand at mural scale. The comic artist whose panel he adapted, Irv Novick, received no credit and no payment.",
    style: "dots",
    faithful: false,
    palette: ["#f2e14c", "#1b3a8f", "#d81e2c", "#f7f4e8", "#101010"]
  },
  {
    title: "Campbell's Soup Cans",
    wiki: "Campbell's Soup Cans",
    artist: "Andy Warhol",
    year: "1962",
    medium: "Synthetic polymer paint on 32 canvases",
    where: "Museum of Modern Art, New York",
    blurb: "Thirty-two canvases, one for every variety Campbell's sold at the time, hung on a shelf like supermarket stock. A nearby gallery responded by stacking real cans in its window, undercutting him on price. Warhol said he painted soup because he had eaten it for lunch every day for twenty years, which is either the shallowest or the most honest artist's statement on record.",
    style: "repeat",
    faithful: false,
    palette: ["#f4f1e6", "#c8102e", "#1a1a1a", "#c9a227"]
  },
  {
    title: "Love Is in the Bin",
    wiki: "Girl with Balloon",
    artist: "Banksy",
    year: "2018",
    medium: "Spray paint and acrylic on canvas, partly shredded",
    where: "Private collection",
    blurb: "Girl with Balloon sold at Sotheby's for just over £1 million, and the instant the hammer fell a shredder hidden in the frame started pulling the canvas through itself. It jammed halfway. Renamed Love Is in the Bin, the half-destroyed work resold three years later for about eighteen times the original price — a self-destruct mechanism that turned out to be the most profitable thing in the room.",
    style: "figure",
    faithful: false,
    palette: ["#f2f0ea", "#1d1d1d", "#d0202f", "#9b9b96"]
  },
  {
    title: "Composition VIII",
    artist: "Wassily Kandinsky",
    year: "1923",
    medium: "Oil on canvas",
    where: "Solomon R. Guggenheim Museum, New York",
    blurb: "Circles, arcs, grids and floating triangles arranged with no reference to anything visible. Kandinsky had synaesthesia and wrote a whole theory assigning sounds and emotions to forms — yellow was a trumpet, a triangle was aggressive. He was teaching at the Bauhaus when he painted this, so the geometry is deliberate: he was trying to make a grammar other people could actually be taught.",
    style: "facets",
    faithful: false,
    palette: ["#f0ece0", "#e4b73c", "#c0392b", "#2a6fb0", "#1b1b1b"]
  },
  {
    title: "Nude Descending a Staircase, No. 2",
    wiki: "Nude Descending a Staircase, No. 2",
    artist: "Marcel Duchamp",
    year: "1912",
    medium: "Oil on canvas",
    where: "Philadelphia Museum of Art",
    blurb: "A figure shattered into overlapping brown facets, each one a frozen instant of the same movement. Duchamp was borrowing directly from chronophotography — the stop-motion studies of Marey and Muybridge — which makes this a painting built from a photographic technology invented to study motion. At the 1913 Armory Show a critic called it 'an explosion in a shingle factory,' and the name stuck for years.",
    style: "facets",
    faithful: false,
    palette: ["#c9a26b", "#8b6136", "#5a3d22", "#e2cfa8", "#2e2013"]
  },
  {
    title: "Autumn Rhythm (Number 30)",
    wiki: "Autumn Rhythm (Number 30)",
    artist: "Jackson Pollock",
    year: "1950",
    medium: "Enamel on canvas",
    where: "Metropolitan Museum of Art, New York",
    blurb: "Pollock laid unstretched canvas on the floor and poured household enamel from sticks and hardened brushes, walking around and into the picture. Physicists who later measured his drip paintings found genuine fractal structure in them, with the fractal dimension climbing steadily across the years he worked this way — a signature that has been used to question attributions.",
    style: "drips",
    faithful: false,
    palette: ["#d9cdb6", "#1a1a1a", "#f3efe4", "#8a6a45", "#4a4a4a"]
  },
  {
    title: "The Starry Night",
    wiki: "The Starry Night",
    artist: "Vincent van Gogh",
    year: "1889",
    medium: "Oil on canvas",
    where: "Museum of Modern Art, New York",
    blurb: "Painted from memory and imagination in an asylum at Saint-Rémy, looking out an east-facing window before sunrise. Van Gogh thought it was a failure. Fluid dynamicists have since found that the luminance variations in the swirls follow the statistical signature of real turbulent flow — a structure that is genuinely hard to produce by hand and that he never saw described.",
    style: "swirl",
    faithful: false,
    palette: ["#0b1b3f", "#1f4b99", "#4d86d6", "#f2d04e", "#0d1a12"]
  },
  {
    title: "The Great Wave off Kanagawa",
    wiki: "The Great Wave off Kanagawa",
    artist: "Katsushika Hokusai",
    year: "c. 1831",
    medium: "Woodblock print",
    where: "Impressions in collections worldwide",
    blurb: "There is no original. It is a print, pulled from carved blocks in the thousands over the life of the edition, and surviving impressions differ visibly because the blocks wore down as the run went on. Its blue is Prussian blue, a synthetic pigment newly imported into Japan, so the most recognisable image in Japanese art depends on a chemical import. Hokusai was about seventy when he made it, and considered his best work still ahead of him.",
    style: "wave",
    faithful: false,
    palette: ["#e8e0cc", "#0f3057", "#2e6f95", "#f5f2e6", "#1b2733"]
  },
  {
    title: "The Scream",
    wiki: "The Scream",
    artist: "Edvard Munch",
    year: "1893",
    medium: "Tempera and crayon on cardboard",
    where: "National Museum, Oslo",
    blurb: "The figure isn't screaming. Munch's own note describes hearing a scream pass through nature while he stood there feeling exhausted, so the figure is covering its ears against it. Someone once pencilled 'Could only have been painted by a madman' onto the canvas; in 2021 the National Museum concluded the handwriting was Munch's own.",
    style: "swirl",
    faithful: false,
    palette: ["#1e2a5a", "#d95f18", "#f2b134", "#7a3b1e", "#0d1330"]
  },
  {
    title: "Mona Lisa",
    wiki: "Mona Lisa",
    artist: "Leonardo da Vinci",
    year: "c. 1503–19",
    medium: "Oil on poplar panel",
    where: "Musée du Louvre, Paris",
    blurb: "It is small — about 77 by 53 centimetres — and it was a fairly ordinary famous painting until it was stolen in 1911 by a museum worker who simply walked out with it under his coat. Crowds queued to look at the empty wall. It came back two years later a global celebrity, which is why the most visited painting on earth owes much of its fame to a theft.",
    style: "figure",
    faithful: false,
    palette: ["#4a3a22", "#8c7444", "#c9ac74", "#2a2113", "#e0cfa8"]
  },
  {
    title: "Girl with a Pearl Earring",
    wiki: "Girl with a Pearl Earring",
    artist: "Johannes Vermeer",
    year: "c. 1665",
    medium: "Oil on canvas",
    where: "Mauritshuis, The Hague",
    blurb: "Not a portrait — it's a tronie, a study of a type or costume rather than a specific person, so there is probably no identifiable sitter to find. Recent imaging suggests the flat dark background was originally a green curtain that has since degraded, and that the 'pearl' is two brushstrokes of white with no outline at all.",
    style: "figure",
    faithful: false,
    palette: ["#1a1c18", "#c8a24a", "#2f5d8a", "#e8d6b8", "#6b3a24"]
  },
  {
    title: "The Night Watch",
    wiki: "The Night Watch",
    artist: "Rembrandt van Rijn",
    year: "1642",
    medium: "Oil on canvas",
    where: "Rijksmuseum, Amsterdam",
    blurb: "It isn't a night scene — centuries of darkened varnish made it look like one, and the name stuck. It was also cut down on all four sides in 1715 to fit a wall, losing two figures from the left permanently; in 2021 the museum used AI trained on Rembrandt's brushwork to reconstruct and print the missing strips. Each militiaman in it paid toward the commission, and they were charged more for a better position.",
    style: "figure",
    faithful: false,
    palette: ["#241a0e", "#7a5a24", "#c9a44a", "#0f0b06", "#a83a2a"]
  },
  {
    title: "Las Meninas",
    wiki: "Las Meninas",
    artist: "Diego Velázquez",
    year: "1656",
    medium: "Oil on canvas",
    where: "Museo del Prado, Madrid",
    blurb: "Velázquez painted himself at work on a canvas we can't see, with the king and queen visible only as a small reflection in a mirror at the back — which means the space the royal couple occupy is roughly where the viewer is standing. Art historians have argued for three centuries about what is actually on the hidden canvas, and the picture has become the standard example of a painting that contains its own act of observation.",
    style: "figure",
    faithful: false,
    palette: ["#2b1f14", "#6b543a", "#c4b39a", "#8f2f2a", "#0e0a06"]
  },
  {
    title: "The Birth of Venus",
    wiki: "The Birth of Venus",
    artist: "Sandro Botticelli",
    year: "c. 1485",
    medium: "Tempera on canvas",
    where: "Uffizi Gallery, Florence",
    blurb: "Painted on canvas rather than the wood panel Botticelli used for its companion piece, the Primavera — canvas was the cheaper support, favoured for works destined for a private house. He used a thin, matte tempera technique with some surfaces finished in real gold, and Venus stands in an anatomically impossible pose — her neck is too long and her left shoulder drops at an angle no shoulder does — which nobody notices, because the rhythm of the line matters more than the anatomy.",
    style: "figure",
    faithful: false,
    palette: ["#a8c4c0", "#dcc9a0", "#f0e6d2", "#5b7f6f", "#c98f5a"]
  },
  {
    title: "The Garden of Earthly Delights",
    wiki: "The Garden of Earthly Delights",
    artist: "Hieronymus Bosch",
    year: "c. 1490–1510",
    medium: "Oil on oak panel triptych",
    where: "Museo del Prado, Madrid",
    blurb: "Close the wings and the outside is a grey sphere: the world on the third day of creation. Open them and you get Eden, then a crowded garden, then hell — where a figure has a fragment of musical notation tattooed across their backside. A student transcribed and recorded it in 2014 and it went viral, though specialists argue the marks were never really readable notation to begin with.",
    style: "scene",
    faithful: false,
    palette: ["#e3d5b0", "#7fa05a", "#3f5f8a", "#b0472c", "#221a12"]
  },
  {
    title: "Impression, Sunrise",
    wiki: "Impression, Sunrise",
    artist: "Claude Monet",
    year: "1872",
    medium: "Oil on canvas",
    where: "Musée Marmottan Monet, Paris",
    blurb: "A hazy view of the port of Le Havre that gave an entire movement its name — and the name came from a hostile review mocking the painting as a mere 'impression', unfinished. The critics were right about one thing: the orange sun is almost exactly as bright as the grey sky behind it, so in a black-and-white photograph it nearly vanishes. It only reads as a sun because of colour, not light.",
    style: "fields",
    faithful: false,
    palette: ["#6d7f92", "#9aa8b4", "#e2803c", "#4a5a68", "#c9b9a8"]
  },
  {
    title: "Water Lilies",
    wiki: "Water Lilies (Monet series)",
    artist: "Claude Monet",
    year: "1896–1926",
    medium: "Oil on canvas",
    where: "Musée de l'Orangerie, Paris, and elsewhere",
    blurb: "Around 250 paintings of the same pond in his own garden, painted over the last thirty years of his life. Monet developed cataracts along the way, which shifted his palette toward reds and yellows; after surgery he repainted some canvases he had finished while unable to see blue properly. The largest panels were designed to wrap around an oval room with no horizon anywhere, so there is nothing to stand back from.",
    style: "fields",
    faithful: false,
    palette: ["#2f5d5a", "#4f8a7a", "#9fc0a0", "#d8c0d0", "#1d3a3e"]
  },
  {
    title: "Nighthawks",
    wiki: "Nighthawks (Hopper)",
    artist: "Edward Hopper",
    year: "1942",
    medium: "Oil on canvas",
    where: "Art Institute of Chicago",
    blurb: "The diner has no door. Look around the whole wraparound window and there is no way in or out, which is a large part of why the picture feels the way it does. Hopper said he was probably painting the loneliness of a large city without meaning to, and that the light — new fluorescent lighting, then a novelty — was what actually interested him.",
    style: "fields",
    faithful: false,
    palette: ["#0f1a2b", "#e0c86a", "#2a6b6b", "#8a2f2a", "#d9cfae"]
  },
  {
    title: "American Gothic",
    wiki: "American Gothic",
    artist: "Grant Wood",
    year: "1930",
    medium: "Oil on beaverboard",
    where: "Art Institute of Chicago",
    blurb: "They are not a married couple — Wood painted a farmer and his daughter, modelled by his dentist and his own sister, who spent years correcting people. He built the whole picture around a house he had spotted in Eldon, Iowa, with an oddly ambitious Gothic window for a small frame cottage. Iowans initially took the painting as an insult.",
    style: "figure",
    faithful: false,
    palette: ["#cfc7ae", "#2b2f3a", "#8a6b3a", "#f2eddf", "#5a5f4a"]
  },
  {
    title: "The Kiss",
    wiki: "The Kiss (Klimt)",
    artist: "Gustav Klimt",
    year: "1907–08",
    medium: "Oil and gold leaf on canvas",
    where: "Belvedere, Vienna",
    blurb: "Klimt's father was a gold engraver, and in this period he was applying real gold leaf directly to canvas, which is why the surface behaves like a mosaic rather than a painting. The ornament is doing structural work: rectangles fall down the man's robe, circles across the woman's, so you can read the two figures apart in an image where everything else has merged into a single gold field.",
    style: "figure",
    faithful: false,
    palette: ["#8a6a12", "#d4af37", "#f0d98a", "#3f2f1a", "#c9584a"]
  },
  {
    title: "Guernica",
    wiki: "Guernica (Picasso)",
    artist: "Pablo Picasso",
    year: "1937",
    medium: "Oil on canvas",
    where: "Museo Reina Sofía, Madrid",
    blurb: "Eleven feet tall, twenty-five feet wide, and painted in about five weeks in black, white and grey after the bombing of a Basque town. Picasso refused to let it go to Spain while Franco lived, so it spent decades at MoMA; it finally arrived in Madrid in 1981. A tapestry copy hangs at the United Nations, and in 2003 it was covered with a large blue curtain while the case for war in Iraq was being made there.",
    style: "facets",
    faithful: false,
    palette: ["#e8e6e0", "#3a3a3a", "#9a9a96", "#151515", "#c4c2bb"]
  },
  {
    title: "Les Demoiselles d'Avignon",
    wiki: "Les Demoiselles d'Avignon",
    artist: "Pablo Picasso",
    year: "1907",
    medium: "Oil on canvas",
    where: "Museum of Modern Art, New York",
    blurb: "Picasso rolled it up and showed it to almost nobody for years — even his allies found it repellent, and Matisse reportedly thought it was an attack on modern painting. Five figures, no single vanishing point, and two faces borrowed from African masks he had seen in a Paris museum. Cubism starts here, and so does a long, uncomfortable conversation about what European modernism took and from whom.",
    style: "facets",
    faithful: false,
    palette: ["#e0b090", "#c0603a", "#3a5a8a", "#e8d8c0", "#2a1a14"]
  },
  {
    title: "The Persistence of Memory",
    wiki: "The Persistence of Memory",
    artist: "Salvador Dalí",
    year: "1931",
    medium: "Oil on canvas",
    where: "Museum of Modern Art, New York",
    blurb: "It is tiny — about 24 by 33 centimetres, smaller than a sheet of A3. Dalí said the melting watches came from watching Camembert soften in the sun, and the cliffs in the background are a real coastline in Catalonia near where he grew up. The pale shape draped in the centre is a distorted self-portrait, asleep.",
    style: "scene",
    faithful: false,
    palette: ["#c9a86a", "#3a5a7a", "#e8d8b0", "#1a2a3a", "#8a6a3a"]
  },
  {
    title: "The Third of May 1808",
    wiki: "The Third of May 1808",
    artist: "Francisco Goya",
    year: "1814",
    medium: "Oil on canvas",
    where: "Museo del Prado, Madrid",
    blurb: "Often called the first modern painting of war: no heroism, no glory, and the firing squad rendered as a faceless machine of backs and rifles. The victim in white throws his arms out in a pose that quotes the crucifixion, and his right hand has a mark on it. Goya painted it six years after the event, once the French had left.",
    style: "scene",
    faithful: false,
    palette: ["#1a1a14", "#d9cf9a", "#8a2a1a", "#4a4438", "#f2ead0"]
  },
  {
    title: "Ophelia",
    wiki: "Ophelia (painting)",
    artist: "John Everett Millais",
    year: "1851–52",
    medium: "Oil on canvas",
    where: "Tate Britain, London",
    blurb: "Millais painted the river first, outdoors, for eleven hours a day over five months, then added the figure in the studio. His model, Elizabeth Siddal, lay in a bathtub kept warm by lamps underneath; the lamps went out, Millais didn't notice, and she caught a serious illness. Every plant in the picture is botanically accurate and chosen for the flower symbolism in Hamlet.",
    style: "scene",
    faithful: false,
    palette: ["#2a3a1a", "#6a8a3a", "#d8cfa0", "#3a4a5a", "#c9b06a"]
  },
  {
    title: "Sunflowers",
    wiki: "Sunflowers (Van Gogh series)",
    artist: "Vincent van Gogh",
    year: "1888",
    medium: "Oil on canvas",
    where: "National Gallery, London, and elsewhere",
    blurb: "Van Gogh painted these to decorate a bedroom for Gauguin, who was coming to stay in Arles, and he was genuinely proud of them — rare for him. He used a new chrome yellow that was cheap, brilliant, and chemically unstable, so the flowers have been quietly browning ever since. Conservators can now model the fading, which means we know these paintings looked considerably louder than they do now.",
    style: "bloom",
    faithful: false,
    palette: ["#c9a227", "#f2c94c", "#8a6a1a", "#e8dcb0", "#5a4a1a"]
  },
  {
    title: "The Two Fridas",
    wiki: "The Two Fridas",
    artist: "Frida Kahlo",
    year: "1939",
    medium: "Oil on canvas",
    where: "Museo de Arte Moderno, Mexico City",
    blurb: "Her largest painting, made the year she divorced Diego Rivera: two versions of herself holding hands, one in a European lace dress and one in Tehuana clothing, hearts exposed and joined by a single artery. The European Frida is clamping the vessel shut with surgical forceps and bleeding onto her own dress. Kahlo painted much of her work using a mirror mounted above her bed.",
    style: "figure",
    faithful: false,
    palette: ["#2a4a5a", "#e8e0d0", "#a81a2a", "#3a6a4a", "#1a1a1a"]
  },
  {
    title: "Untitled Film Still #21",
    wiki: "Untitled Film Stills",
    artist: "Cindy Sherman",
    year: "1978",
    medium: "Gelatin silver print",
    where: "Museum of Modern Art, New York (edition)",
    blurb: "A young woman in a city, shot from below, looking off-frame — it reads instantly as a still from a film you half remember. There is no film. Sherman photographed herself in about seventy of these, playing every role and operating the camera, inventing a genre of picture that is entirely made of other pictures' conventions. She has consistently refused to call any of them self-portraits.",
    style: "figure",
    faithful: false,
    palette: ["#c8c8c4", "#6a6a68", "#2a2a28", "#f0f0ec", "#9a9a96"]
  },
  {
    title: "The Dinner Party",
    wiki: "The Dinner Party",
    artist: "Judy Chicago",
    year: "1974–79",
    medium: "Ceramic, porcelain, and textile installation",
    where: "Brooklyn Museum, New York",
    blurb: "A triangular banquet table with thirty-nine place settings, each one for a woman from history, with another 999 names inscribed on the tile floor beneath. It took five years and hundreds of collaborators working in ceramics and needlework — crafts that had been filed as women's work and therefore excluded from fine art, which was precisely the argument. It toured to enormous crowds and scathing reviews before any museum would take it permanently.",
    style: "scene",
    faithful: false,
    palette: ["#e8dcc8", "#c96a8a", "#8a6ac9", "#d9b06a", "#3a2a3a"]
  }
];

// "On this day" events keyed by MM-DD. A curated set of dates; days not
// present fall back to a deterministic pick from HISTORY_FALLBACK.
const HISTORY_BY_DATE = {
  "01-01": { year: 1983, text: "ARPANET switched over to TCP/IP in a single 'flag day' cutover — the moment the internet as we know it began speaking its native language." },
  "01-03": { year: 2009, text: "The Bitcoin genesis block was mined, with a Times headline about bank bailouts embedded in it as a timestamp and a comment." },
  "01-09": { year: 2007, text: "Steve Jobs introduced the iPhone at Macworld, demoing a device so unfinished the team had to follow an exact script to keep it from crashing on stage." },
  "01-15": { year: 2001, text: "Wikipedia launched — originally just a side experiment to feed articles into a more traditional, expert-reviewed encyclopedia project." },
  "01-24": { year: 1984, text: "The Macintosh went on sale, the first mass-market computer built around a mouse, windows, and proportional typefaces." },
  "01-28": { year: 1912, text: "Jackson Pollock was born. He would abandon the easel entirely, laying canvas on the floor and painting from above." },
  "02-04": { year: 2004, text: "Facebook launched from a Harvard dorm room, restricted at first to people with a harvard.edu email address." },
  "02-10": { year: 1996, text: "Deep Blue beat Garry Kasparov in a single game — the first time a computer defeated a reigning world champion under tournament conditions. Kasparov won the match anyway." },
  "02-14": { year: 1876, text: "Alexander Graham Bell filed his telephone patent, reportedly hours ahead of a rival filing on the same principle." },
  "02-16": { year: 1978, text: "The first computerized bulletin board system went online in Chicago, built during a blizzard. Online community predates the web by more than a decade." },
  "02-24": { year: 1955, text: "Steve Jobs was born. He later credited a college calligraphy class he audited for the Mac's typography." },
  "03-06": { year: 1475, text: "Michelangelo was born. He always described himself as a sculptor, and considered the Sistine Chapel ceiling a distraction from that." },
  "03-12": { year: 1989, text: "Tim Berners-Lee circulated a proposal at CERN for a hypertext system. His manager's note on the cover read: 'Vague but exciting.'" },
  "03-14": { year: 1879, text: "Albert Einstein was born — on what would later, by coincidence of notation, also become Pi Day." },
  "03-15": { year: 1985, text: "symbolics.com was registered, the first .com domain in existence. Only five more followed that year." },
  "03-21": { year: 2006, text: "The first tweet was posted: 'just setting up my twttr.' The 140-character limit existed to fit inside an SMS." },
  "03-30": { year: 1853, text: "Vincent van Gogh was born. He didn't start painting seriously until his late twenties and was dead within a decade." },
  "03-31": { year: 1889, text: "The Eiffel Tower opened. Leading French artists had signed a public letter calling it a monstrous, useless iron chimney." },
  "04-01": { year: 1976, text: "Apple Computer was founded. A third co-founder sold his 10% stake twelve days later for $800." },
  "04-03": { year: 1973, text: "Martin Cooper made the first handheld mobile phone call, standing on a Manhattan sidewalk — to his chief rival at Bell Labs, to tell him he'd done it first." },
  "04-04": { year: 1975, text: "Microsoft was founded to write a BASIC interpreter for a computer its founders had never actually seen in person." },
  "04-12": { year: 1961, text: "Yuri Gagarin became the first human in space, in a capsule flown almost entirely by automated control." },
  "04-15": { year: 1452, text: "Leonardo da Vinci was born. He wrote his notebooks in mirror script and left most of his projects unfinished." },
  "04-23": { year: 2005, text: "The first YouTube video was uploaded: 19 seconds of a co-founder standing in front of the elephants at the San Diego Zoo." },
  "04-30": { year: 1993, text: "CERN released the World Wide Web software into the public domain, royalty-free. Arguably the single most valuable thing anyone has ever given away." },
  "05-11": { year: 1904, text: "Salvador Dalí was born. He claimed to induce his melting imagery by napping in a chair holding a key over a metal plate." },
  "05-16": { year: 1929, text: "The first Academy Awards were handed out in a 15-minute ceremony. The winners had been announced three months earlier." },
  "05-17": { year: 1902, text: "An archaeologist noticed a gear embedded in a corroded lump from a Greek shipwreck — the Antikythera mechanism, a 2,000-year-old geared computer." },
  "05-22": { year: 1980, text: "Pac-Man was released in Japan, designed deliberately to appeal to players who had no interest in shooting things." },
  "05-24": { year: 1844, text: "Samuel Morse sent 'What hath God wrought' over the first long-distance telegraph line, collapsing the time it took news to cross a continent." },
  "05-25": { year: 1977, text: "Star Wars opened on fewer than 40 screens. The effects work behind it created the company that later became Pixar." },
  "05-29": { year: 1913, text: "The premiere of Stravinsky's The Rite of Spring in Paris set off a riot in the theater. It's now standard repertoire." },
  "06-01": { year: 1967, text: "Sgt. Pepper's Lonely Hearts Club Band was released, with a collaged cover so elaborate the band had to get legal clearance for the faces on it." },
  "06-08": { year: 1955, text: "Tim Berners-Lee was born. He would later refuse to patent the web." },
  "06-21": { year: 1948, text: "The Manchester 'Baby' ran the first program ever executed from electronic memory. It took 52 minutes to find the highest factor of a number." },
  "06-23": { year: 1912, text: "Alan Turing was born. His 1936 paper defined what a computer is before any computer existed." },
  "07-04": { year: 1997, text: "Mars Pathfinder landed and released Sojourner, the first rover to drive on another planet. It used airbags to bounce to a stop." },
  "07-06": { year: 1907, text: "Frida Kahlo was born. She painted most of her self-portraits using a mirror mounted above her bed." },
  "07-20": { year: 1969, text: "Apollo 11 landed while its guidance computer threw overflow alarms. The software had been designed to shed low-priority tasks instead of crashing — and that's why they didn't abort." },
  "08-01": { year: 1981, text: "MTV launched. The first video it played was 'Video Killed the Radio Star.'" },
  "08-06": { year: 1991, text: "Tim Berners-Lee posted a short public summary of the World Wide Web project to a Usenet newsgroup — the web's first public announcement." },
  "08-09": { year: 1995, text: "Netscape went public without ever having turned a profit, and the price more than doubled on day one. The dot-com era had a starting gun." },
  "08-12": { year: 1981, text: "IBM introduced the Personal Computer. Its open architecture let competitors clone it, which IBM had not adequately planned for." },
  "08-21": { year: 1911, text: "The Mona Lisa was stolen from the Louvre by a museum worker who simply walked out with it under his smock. The theft is what made it famous." },
  "09-04": { year: 1998, text: "Google was incorporated in a garage. Its founders had earlier tried to sell the technology for about $1 million and found no buyer." },
  "09-08": { year: 1504, text: "Michelangelo's David was unveiled in Florence, carved from a block of marble two other sculptors had already given up on." },
  "09-09": { year: 1947, text: "Operators pulled a moth out of the Harvard Mark II and taped it into the logbook: 'First actual case of bug being found.'" },
  "09-19": { year: 1982, text: "Scott Fahlman proposed :-) on a Carnegie Mellon message board to mark jokes. Every emoji descends from that suggestion." },
  "10-04": { year: 1957, text: "Sputnik 1 launched. The panic it caused in the U.S. led directly to the agency that funded ARPANET." },
  "10-05": { year: 2018, text: "Banksy's Girl with Balloon shredded itself seconds after selling at Sotheby's, via a mechanism hidden in the frame for years." },
  "10-23": { year: 2001, text: "Apple introduced the iPod. The press response was largely a shrug about an expensive music player with no wireless." },
  "10-25": { year: 1881, text: "Pablo Picasso was born. He was a fully trained academic realist by his teens and spent the rest of his life dismantling that training." },
  "10-28": { year: 1955, text: "Bill Gates was born. He wrote his first program, a tic-tac-toe game, at thirteen." },
  "10-29": { year: 1969, text: "The first message was sent over ARPANET. They typed 'LOGIN,' the system crashed after two characters, and the internet's first word was 'LO.'" },
  "10-30": { year: 1938, text: "Orson Welles broadcast The War of the Worlds as simulated news bulletins — an early demonstration that the format of a medium can be more persuasive than its content." },
  "11-01": { year: 1512, text: "The Sistine Chapel ceiling was revealed to the public after four years of work Michelangelo had tried to refuse." },
  "11-04": { year: 1922, text: "Howard Carter found the sealed entrance to Tutankhamun's tomb, preserving the largest intact collection of ancient Egyptian art ever recovered." },
  "11-09": { year: 1989, text: "The Berlin Wall opened. Within days, sections of it were being cut up and sold as art objects." },
  "11-18": { year: 1928, text: "Steamboat Willie premiered — not the first Mickey Mouse cartoon, but the first with synchronized sound, which is why it's the one everyone remembers." },
  "11-22": { year: 1995, text: "Toy Story opened, the first feature film animated entirely by computer. Every frame was rendered from scratch by a farm of machines running for months." },
  "11-30": { year: 2022, text: "ChatGPT was released as a low-key research preview. It reached a million users in five days." },
  "12-09": { year: 1968, text: "Douglas Engelbart's 'Mother of All Demos' showed the mouse, hypertext, windows, video conferencing, and collaborative editing — in one 90-minute session, decades before any of it shipped." },
  "12-10": { year: 1815, text: "Ada Lovelace was born. Her notes on Babbage's Analytical Engine include the first published algorithm intended for a machine." },
  "12-12": { year: 1913, text: "The Mona Lisa was recovered in Florence, two years after its theft, when the thief tried to sell it to an art dealer." },
  "12-16": { year: 1947, text: "Bell Labs built the first working transistor. Nearly every device you have ever used contains descendants of it, now measured in the billions per chip." },
  "12-17": { year: 1903, text: "The Wright brothers flew. The longest flight that day covered 852 feet — shorter than the wingspan of a modern airliner's route to the gate." },
  "12-21": { year: 1937, text: "Snow White premiered, the first full-length cel-animated feature. The industry had called it Disney's Folly." },
  "12-25": { year: 1990, text: "Tim Berners-Lee got the first web browser and web server talking to each other — the first successful client-server exchange over the World Wide Web." }
};

const HISTORY_FALLBACK = [
  { year: 1971, text: "Intel shipped the 4004, the first commercial microprocessor. It held 2,300 transistors and was designed for a desktop calculator." },
  { year: 1843, text: "Ada Lovelace published notes describing how a machine could manipulate symbols, not just numbers — the conceptual leap from calculator to computer." },
  { year: 1936, text: "Alan Turing described a machine that could simulate any other machine, defining the limits of computation before hardware existed to test it." },
  { year: 1948, text: "Claude Shannon published 'A Mathematical Theory of Communication,' inventing information theory and the bit in one paper." },
  { year: 1969, text: "Unix was started at Bell Labs as an unofficial project on a spare minicomputer nobody else wanted." },
  { year: 1973, text: "The Xerox Alto was built with a bitmapped screen, a mouse, and windows. Xerox never sold it, and visitors took the ideas elsewhere." },
  { year: 1977, text: "RSA public-key cryptography was published, making it possible to exchange secrets with strangers you've never met." },
  { year: 1984, text: "The first fully computer-generated character in a feature film appeared, stitched together frame by frame on machines slower than a modern thermostat." },
  { year: 1991, text: "Linux was announced as a hobby project that would 'not be big and professional like gnu.'" },
  { year: 1994, text: "The QR code was invented to track car parts on an assembly line, deliberately designed to still scan when partly damaged." },
  { year: 2007, text: "The smartphone era began in earnest, collapsing the camera, map, music player, and computer into one object." },
  { year: 1957, text: "The first digital image was scanned — a 176-pixel-square photograph, the ancestor of every JPEG." },
  { year: 1962, text: "Spacewar!, one of the first video games, was written for fun on a $120,000 research computer and given away for free." },
  { year: 1975, text: "A university researcher digitized a teapot as a graphics test object. It became the most rendered shape in the history of computing." },
  { year: 2021, text: "Researchers dated a warty pig painted on a cave wall in Sulawesi to at least 45,500 years ago — the oldest known figurative artwork anywhere." },
  { year: 1420, text: "Brunelleschi worked out linear perspective, giving European painting a mathematics of depth and changing how a flat surface could lie convincingly." },
  { year: 1665, text: "Vermeer painted Girl with a Pearl Earring — technically not a portrait but a tronie, a study of a type rather than a person." },
  { year: 1831, text: "Hokusai published The Great Wave, using a synthetic blue pigment newly imported from Europe." },
  { year: 1874, text: "The first Impressionist exhibition opened in Paris after the official Salon rejected the work. The movement's name came from a hostile review." },
  { year: 1907, text: "Picasso finished Les Demoiselles d'Avignon and showed it to almost no one for years. It broke the picture plane open and started Cubism." },
  { year: 1917, text: "Duchamp submitted a factory-made urinal to an exhibition as sculpture, and the question of what counts as art never fully closed again." },
  { year: 1962, text: "Pop Art arrived in the gallery, insisting that soup cans and comic panels were legitimate subjects for serious painting." },
  { year: 1968, text: "The exhibition Cybernetic Serendipity in London showed computer-generated art, music, and poetry to the public for the first time." },
  { year: 1985, text: "Desktop publishing arrived — a computer, a page layout program, and a laser printer put typesetting on a desk instead of in a print shop." }
];
